# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_historie.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(903, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidgetHistory = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetHistory.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetHistory.setObjectName("tableWidgetHistory")
        self.tableWidgetHistory.setColumnCount(3)
        self.tableWidgetHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidgetHistory)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(Dialog)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout.addWidget(self.lineEditSearch)
        self.pushButtonSearch = QtWidgets.QPushButton(Dialog)
        self.pushButtonSearch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pypordb/suchen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSearch.setIcon(icon1)
        self.pushButtonSearch.setAutoDefault(False)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout.addWidget(self.pushButtonSearch)
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.labelLines = QtWidgets.QLabel(Dialog)
        self.labelLines.setText("")
        self.labelLines.setObjectName("labelLines")
        self.horizontalLayout.addWidget(self.labelLines)
        spacerItem = QtWidgets.QSpacerItem(668, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonGo = QtWidgets.QPushButton(Dialog)
        self.pushButtonGo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pypordb/application-x-executable.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGo.setIcon(icon2)
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.horizontalLayout.addWidget(self.pushButtonGo)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Dialog)
        self.pushButtonAbbrechen.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pypordb/dialog-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAbbrechen.setIcon(icon3)
        self.pushButtonAbbrechen.setAutoDefault(False)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.horizontalLayout.addWidget(self.pushButtonAbbrechen)
        self.pushButtonClear = QtWidgets.QPushButton(Dialog)
        self.pushButtonClear.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pypordb/user-trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClear.setIcon(icon4)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout.addWidget(self.pushButtonClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "History"))
        self.tableWidgetHistory.setWhatsThis(_translate("Dialog", "Here you see your last search command. You can repeat one search by marking the line and click on execute."))
        self.tableWidgetHistory.setSortingEnabled(True)
        item = self.tableWidgetHistory.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Select"))
        item = self.tableWidgetHistory.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Command"))
        item = self.tableWidgetHistory.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Timestamp"))
        self.pushButtonSearch.setToolTip(_translate("Dialog", "Search in history, Ctrl+S"))
        self.pushButtonSearch.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.label_1.setText(_translate("Dialog", "Lines: "))
        self.pushButtonGo.setToolTip(_translate("Dialog", "Execute marked line"))
        self.pushButtonAbbrechen.setToolTip(_translate("Dialog", "<html><head/><body><p>Cancel</p></body></html>"))
        self.pushButtonClear.setToolTip(_translate("Dialog", "<html><head/><body><p>Clear history: delete all entries except for the last 50 entries</p></body></html>"))

