# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_suche_video.ui'
#
# Created: Tue Mar 13 22:32:22 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 983, 646))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidgetVideo = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.listWidgetVideo.setMinimumSize(QtCore.QSize(20, 0))
        self.listWidgetVideo.setMaximumSize(QtCore.QSize(20, 16777215))
        self.listWidgetVideo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidgetVideo.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.listWidgetVideo.setViewMode(QtGui.QListView.ListMode)
        self.listWidgetVideo.setObjectName("listWidgetVideo")
        self.horizontalLayout.addWidget(self.listWidgetVideo)
        self.textEditVideo = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditVideo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditVideo.setObjectName("textEditVideo")
        self.horizontalLayout.addWidget(self.textEditVideo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_insgesamt = QtGui.QLabel(Dialog)
        self.label_insgesamt.setText("")
        self.label_insgesamt.setObjectName("label_insgesamt")
        self.horizontalLayout_2.addWidget(self.label_insgesamt)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_vorhanden = QtGui.QLabel(Dialog)
        self.label_vorhanden.setText("")
        self.label_vorhanden.setObjectName("label_vorhanden")
        self.horizontalLayout_2.addWidget(self.label_vorhanden)
        spacerItem = QtGui.QSpacerItem(378, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonSuchen = QtGui.QPushButton(Dialog)
        self.pushButtonSuchen.setObjectName("pushButtonSuchen")
        self.horizontalLayout_2.addWidget(self.pushButtonSuchen)
        self.pushButtonAnzeigen = QtGui.QPushButton(Dialog)
        self.pushButtonAnzeigen.setObjectName("pushButtonAnzeigen")
        self.horizontalLayout_2.addWidget(self.pushButtonAnzeigen)
        self.pushButtonAbbrechen = QtGui.QPushButton(Dialog)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.horizontalLayout_2.addWidget(self.pushButtonAbbrechen)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Search in existing movies", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Enter text (Ctrl+V)", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetVideo.setToolTip(QtGui.QApplication.translate("Dialog", "Presentation of the existing movies", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetVideo.setWhatsThis(QtGui.QApplication.translate("Dialog", "Presentation of the existing movies", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditVideo.setWhatsThis(QtGui.QApplication.translate("Dialog", "Insert text (Ctrl+v)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "overall:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "available:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setToolTip(QtGui.QApplication.translate("Dialog", "Start search (Ctrl+S)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setWhatsThis(QtGui.QApplication.translate("Dialog", "Starts searching", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAnzeigen.setToolTip(QtGui.QApplication.translate("Dialog", "Shows movies (Ctrl+D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAnzeigen.setWhatsThis(QtGui.QApplication.translate("Dialog", "Shows avaible movies", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAnzeigen.setText(QtGui.QApplication.translate("Dialog", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAnzeigen.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAbbrechen.setToolTip(QtGui.QApplication.translate("Dialog", "Cancel (Esc)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAbbrechen.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

