# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_darsteller_suchen.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DarstellerSuche(object):
    def setupUi(self, DarstellerSuche):
        DarstellerSuche.setObjectName("DarstellerSuche")
        DarstellerSuche.resize(867, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DarstellerSuche.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(DarstellerSuche)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(DarstellerSuche)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxDarstellerSucheGeschlecht = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheGeschlecht.setObjectName("comboBoxDarstellerSucheGeschlecht")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pypordb/female.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheGeschlecht.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pypordb/male.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheGeschlecht.addItem(icon2, "")
        self.gridLayout.addWidget(self.comboBoxDarstellerSucheGeschlecht, 1, 1, 1, 1)
        self.dateEditDarstellerSucheAb = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditDarstellerSucheAb.setMinimumDate(QtCore.QDate(1752, 9, 14))
        self.dateEditDarstellerSucheAb.setCalendarPopup(True)
        self.dateEditDarstellerSucheAb.setObjectName("dateEditDarstellerSucheAb")
        self.gridLayout.addWidget(self.dateEditDarstellerSucheAb, 3, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(661, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.comboBoxDarstellerSucheNation = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheNation.setObjectName("comboBoxDarstellerSucheNation")
        self.gridLayout.addWidget(self.comboBoxDarstellerSucheNation, 6, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(631, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.comboBoxDarstellerSucheEthnic = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheEthnic.setObjectName("comboBoxDarstellerSucheEthnic")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.comboBoxDarstellerSucheEthnic.setItemText(0, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pypordb/white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheEthnic.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pypordb/yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheEthnic.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pypordb/black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheEthnic.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("pypordb/brown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheEthnic.addItem(icon6, "")
        self.gridLayout.addWidget(self.comboBoxDarstellerSucheEthnic, 8, 1, 1, 1)
        self.lineEditDarstellerSuche = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditDarstellerSuche.setObjectName("lineEditDarstellerSuche")
        self.gridLayout.addWidget(self.lineEditDarstellerSuche, 0, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(631, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.comboBoxDarstellerSucheTattoo = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheTattoo.setObjectName("comboBoxDarstellerSucheTattoo")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.comboBoxDarstellerSucheTattoo.setItemText(0, "")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.gridLayout.addWidget(self.comboBoxDarstellerSucheTattoo, 7, 1, 1, 1)
        self.lineEditDarstellerSucheTattoo = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditDarstellerSucheTattoo.setObjectName("lineEditDarstellerSucheTattoo")
        self.gridLayout.addWidget(self.lineEditDarstellerSucheTattoo, 7, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(661, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(491, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 8, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.comboBoxDarstellerSucheHaar = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheHaar.setObjectName("comboBoxDarstellerSucheHaar")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.comboBoxDarstellerSucheHaar.setItemText(0, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("pypordb/blond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheHaar.addItem(icon7, "")
        self.comboBoxDarstellerSucheHaar.addItem(icon6, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("pypordb/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerSucheHaar.addItem(icon8, "")
        self.comboBoxDarstellerSucheHaar.addItem(icon5, "")
        self.gridLayout.addWidget(self.comboBoxDarstellerSucheHaar, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEditDarstellerSucheBis = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditDarstellerSucheBis.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEditDarstellerSucheBis.setCalendarPopup(True)
        self.dateEditDarstellerSucheBis.setObjectName("dateEditDarstellerSucheBis")
        self.gridLayout.addWidget(self.dateEditDarstellerSucheBis, 4, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditActor1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditActor1.setObjectName("lineEditActor1")
        self.horizontalLayout.addWidget(self.lineEditActor1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.lineEditActor2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditActor2.setObjectName("lineEditActor2")
        self.horizontalLayout.addWidget(self.lineEditActor2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.lineEditActor3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditActor3.setObjectName("lineEditActor3")
        self.horizontalLayout.addWidget(self.lineEditActor3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 3)
        self.verticalLayout.addWidget(self.groupBox)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButtonSuchen = QtWidgets.QPushButton(DarstellerSuche)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("pypordb/suchen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSuchen.setIcon(icon9)
        self.pushButtonSuchen.setObjectName("pushButtonSuchen")
        self.hboxlayout.addWidget(self.pushButtonSuchen)
        self.pushButtonRefresh = QtWidgets.QPushButton(DarstellerSuche)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("pypordb/clear_l.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon10)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.hboxlayout.addWidget(self.pushButtonRefresh)
        self.pushButtonCancel = QtWidgets.QPushButton(DarstellerSuche)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("pypordb/dialog-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon11)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.hboxlayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DarstellerSuche)
        QtCore.QMetaObject.connectSlotsByName(DarstellerSuche)
        DarstellerSuche.setTabOrder(self.lineEditDarstellerSuche, self.comboBoxDarstellerSucheGeschlecht)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheGeschlecht, self.lineEditActor1)
        DarstellerSuche.setTabOrder(self.lineEditActor1, self.lineEditActor2)
        DarstellerSuche.setTabOrder(self.lineEditActor2, self.lineEditActor3)
        DarstellerSuche.setTabOrder(self.lineEditActor3, self.dateEditDarstellerSucheAb)
        DarstellerSuche.setTabOrder(self.dateEditDarstellerSucheAb, self.dateEditDarstellerSucheBis)
        DarstellerSuche.setTabOrder(self.dateEditDarstellerSucheBis, self.comboBoxDarstellerSucheHaar)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheHaar, self.comboBoxDarstellerSucheNation)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheNation, self.comboBoxDarstellerSucheTattoo)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheTattoo, self.lineEditDarstellerSucheTattoo)
        DarstellerSuche.setTabOrder(self.lineEditDarstellerSucheTattoo, self.comboBoxDarstellerSucheEthnic)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheEthnic, self.pushButtonSuchen)
        DarstellerSuche.setTabOrder(self.pushButtonSuchen, self.pushButtonRefresh)
        DarstellerSuche.setTabOrder(self.pushButtonRefresh, self.pushButtonCancel)

    def retranslateUi(self, DarstellerSuche):
        _translate = QtCore.QCoreApplication.translate
        DarstellerSuche.setWindowTitle(_translate("DarstellerSuche", "Search actor"))
        self.groupBox.setTitle(_translate("DarstellerSuche", "Search criteria"))
        self.label_2.setText(_translate("DarstellerSuche", "Gender"))
        self.comboBoxDarstellerSucheGeschlecht.setItemText(0, _translate("DarstellerSuche", "w"))
        self.comboBoxDarstellerSucheGeschlecht.setItemText(1, _translate("DarstellerSuche", "m"))
        self.dateEditDarstellerSucheAb.setWhatsThis(_translate("DarstellerSuche", "Date when the actor has been added to the PorDB database"))
        self.dateEditDarstellerSucheAb.setDisplayFormat(_translate("DarstellerSuche", "dd.MM.yyyy"))
        self.label_9.setText(_translate("DarstellerSuche", "Has acted with"))
        self.label_3.setText(_translate("DarstellerSuche", "Date from"))
        self.comboBoxDarstellerSucheEthnic.setItemText(1, _translate("DarstellerSuche", "w"))
        self.comboBoxDarstellerSucheEthnic.setItemText(2, _translate("DarstellerSuche", "a"))
        self.comboBoxDarstellerSucheEthnic.setItemText(3, _translate("DarstellerSuche", "s"))
        self.comboBoxDarstellerSucheEthnic.setItemText(4, _translate("DarstellerSuche", "l"))
        self.label_5.setText(_translate("DarstellerSuche", "Hair color"))
        self.label_4.setText(_translate("DarstellerSuche", "Date to"))
        self.label_7.setText(_translate("DarstellerSuche", "Tattoo"))
        self.comboBoxDarstellerSucheTattoo.setItemText(1, _translate("DarstellerSuche", "yes"))
        self.comboBoxDarstellerSucheTattoo.setItemText(2, _translate("DarstellerSuche", "no"))
        self.label_8.setText(_translate("DarstellerSuche", "Ethnic"))
        self.label_6.setText(_translate("DarstellerSuche", "Nation"))
        self.comboBoxDarstellerSucheHaar.setItemText(1, _translate("DarstellerSuche", "bl"))
        self.comboBoxDarstellerSucheHaar.setItemText(2, _translate("DarstellerSuche", "br"))
        self.comboBoxDarstellerSucheHaar.setItemText(3, _translate("DarstellerSuche", "r"))
        self.comboBoxDarstellerSucheHaar.setItemText(4, _translate("DarstellerSuche", "s"))
        self.label.setText(_translate("DarstellerSuche", "Name"))
        self.dateEditDarstellerSucheBis.setWhatsThis(_translate("DarstellerSuche", "Date when the actor has been added to the PorDB database"))
        self.dateEditDarstellerSucheBis.setDisplayFormat(_translate("DarstellerSuche", "dd.MM.yyyy"))
        self.label_10.setText(_translate("DarstellerSuche", "and"))
        self.label_11.setText(_translate("DarstellerSuche", "and"))
        self.pushButtonSuchen.setToolTip(_translate("DarstellerSuche", "<html><head/><body><p>Search, enter</p></body></html>"))
        self.pushButtonSuchen.setText(_translate("DarstellerSuche", "Search"))
        self.pushButtonSuchen.setShortcut(_translate("DarstellerSuche", "Enter"))
        self.pushButtonRefresh.setToolTip(_translate("DarstellerSuche", "<html><head/><body><p>Clear all search fields, alt+L</p></body></html>"))
        self.pushButtonRefresh.setText(_translate("DarstellerSuche", "Clear all search fields"))
        self.pushButtonRefresh.setShortcut(_translate("DarstellerSuche", "Alt+L"))
        self.pushButtonCancel.setToolTip(_translate("DarstellerSuche", "<html><head/><body><p>Cancel, esc</p></body></html>"))
        self.pushButtonCancel.setText(_translate("DarstellerSuche", "Cancel"))

