# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_iafd.ui'
#
# Created: Tue Mar 13 22:32:23 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DatenausderIAFD(object):
    def setupUi(self, DatenausderIAFD):
        DatenausderIAFD.setObjectName("DatenausderIAFD")
        DatenausderIAFD.resize(937, 573)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatenausderIAFD.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(DatenausderIAFD)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxBild = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxBild.setText("")
        self.checkBoxBild.setObjectName("checkBoxBild")
        self.horizontalLayout.addWidget(self.checkBoxBild)
        self.labelBild = QtGui.QLabel(DatenausderIAFD)
        self.labelBild.setMinimumSize(QtCore.QSize(231, 251))
        self.labelBild.setObjectName("labelBild")
        self.horizontalLayout.addWidget(self.labelBild)
        self.labelName = QtGui.QLabel(DatenausderIAFD)
        self.labelName.setEnabled(True)
        self.labelName.setMinimumSize(QtCore.QSize(401, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout.addWidget(self.labelName)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxName = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxName.setText("")
        self.checkBoxName.setObjectName("checkBoxName")
        self.gridLayout.addWidget(self.checkBoxName, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(DatenausderIAFD)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.lineEditName = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 2, 1, 1)
        self.checkBoxGeschlecht = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxGeschlecht.setText("")
        self.checkBoxGeschlecht.setObjectName("checkBoxGeschlecht")
        self.gridLayout.addWidget(self.checkBoxGeschlecht, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(DatenausderIAFD)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.lineEditGeschlecht = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditGeschlecht.setObjectName("lineEditGeschlecht")
        self.gridLayout.addWidget(self.lineEditGeschlecht, 1, 2, 1, 1)
        self.checkBoxPseudo = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxPseudo.setText("")
        self.checkBoxPseudo.setObjectName("checkBoxPseudo")
        self.gridLayout.addWidget(self.checkBoxPseudo, 2, 0, 1, 1)
        self.label = QtGui.QLabel(DatenausderIAFD)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.lineEditPseudo = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditPseudo.setObjectName("lineEditPseudo")
        self.gridLayout.addWidget(self.lineEditPseudo, 2, 2, 1, 1)
        self.checkBoxGeboren = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxGeboren.setText("")
        self.checkBoxGeboren.setObjectName("checkBoxGeboren")
        self.gridLayout.addWidget(self.checkBoxGeboren, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(DatenausderIAFD)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.labelGeboren = QtGui.QLabel(DatenausderIAFD)
        self.labelGeboren.setObjectName("labelGeboren")
        self.gridLayout.addWidget(self.labelGeboren, 3, 2, 1, 1)
        self.checkBoxLand = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxLand.setText("")
        self.checkBoxLand.setObjectName("checkBoxLand")
        self.gridLayout.addWidget(self.checkBoxLand, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(DatenausderIAFD)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.lineEditLand = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditLand.setObjectName("lineEditLand")
        self.gridLayout.addWidget(self.lineEditLand, 4, 2, 1, 1)
        self.checkBoxEthnic = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxEthnic.setText("")
        self.checkBoxEthnic.setObjectName("checkBoxEthnic")
        self.gridLayout.addWidget(self.checkBoxEthnic, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(DatenausderIAFD)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.lineEditEthnic = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditEthnic.setObjectName("lineEditEthnic")
        self.gridLayout.addWidget(self.lineEditEthnic, 5, 2, 1, 1)
        self.checkBoxHaare = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxHaare.setText("")
        self.checkBoxHaare.setObjectName("checkBoxHaare")
        self.gridLayout.addWidget(self.checkBoxHaare, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(DatenausderIAFD)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.lineEditHaare = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditHaare.setObjectName("lineEditHaare")
        self.gridLayout.addWidget(self.lineEditHaare, 6, 2, 1, 1)
        self.checkBoxTattos = QtGui.QCheckBox(DatenausderIAFD)
        self.checkBoxTattos.setText("")
        self.checkBoxTattos.setObjectName("checkBoxTattos")
        self.gridLayout.addWidget(self.checkBoxTattos, 7, 0, 1, 1)
        self.label_7 = QtGui.QLabel(DatenausderIAFD)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 1, 1, 1)
        self.lineEditTattos = QtGui.QLineEdit(DatenausderIAFD)
        self.lineEditTattos.setObjectName("lineEditTattos")
        self.gridLayout.addWidget(self.lineEditTattos, 7, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonUebernehmen = QtGui.QPushButton(DatenausderIAFD)
        self.pushButtonUebernehmen.setObjectName("pushButtonUebernehmen")
        self.horizontalLayout_2.addWidget(self.pushButtonUebernehmen)
        self.pushButtonCancel = QtGui.QPushButton(DatenausderIAFD)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(DatenausderIAFD)
        QtCore.QMetaObject.connectSlotsByName(DatenausderIAFD)

    def retranslateUi(self, DatenausderIAFD):
        DatenausderIAFD.setWindowTitle(QtGui.QApplication.translate("DatenausderIAFD", "Data from the IAFD", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBild.setText(QtGui.QApplication.translate("DatenausderIAFD", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelName.setText(QtGui.QApplication.translate("DatenausderIAFD", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DatenausderIAFD", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DatenausderIAFD", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DatenausderIAFD", "Alias:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DatenausderIAFD", "Born:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGeboren.setText(QtGui.QApplication.translate("DatenausderIAFD", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DatenausderIAFD", "Country:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DatenausderIAFD", "Ethnic:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DatenausderIAFD", "Hair color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DatenausderIAFD", "Tattoos:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUebernehmen.setText(QtGui.QApplication.translate("DatenausderIAFD", "Adopt marked data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("DatenausderIAFD", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

