# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_hauptdialog.ui'
#
# Created: Mon Feb 24 14:54:55 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1920, 1015)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_akt_verzeichnis = QtGui.QLabel(self.layoutWidget)
        self.label_akt_verzeichnis.setObjectName(_fromUtf8("label_akt_verzeichnis"))
        self.horizontalLayout_2.addWidget(self.label_akt_verzeichnis)
        self.pushButtonRefresh = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRefresh.sizePolicy().hasHeightForWidth())
        self.pushButtonRefresh.setSizePolicy(sizePolicy)
        self.pushButtonRefresh.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButtonRefresh.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/appointment-recurring.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon1)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout_2.addWidget(self.pushButtonRefresh)
        self.pushButtonDir = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDir.sizePolicy().hasHeightForWidth())
        self.pushButtonDir.setSizePolicy(sizePolicy)
        self.pushButtonDir.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButtonDir.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/folder.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pushButtonDir.setIcon(icon2)
        self.pushButtonDir.setObjectName(_fromUtf8("pushButtonDir"))
        self.horizontalLayout_2.addWidget(self.pushButtonDir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidgetBilderAktuell = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidgetBilderAktuell.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidgetBilderAktuell.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetBilderAktuell.setDragEnabled(True)
        self.tableWidgetBilderAktuell.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.tableWidgetBilderAktuell.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetBilderAktuell.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetBilderAktuell.setObjectName(_fromUtf8("tableWidgetBilderAktuell"))
        self.tableWidgetBilderAktuell.setColumnCount(0)
        self.tableWidgetBilderAktuell.setRowCount(0)
        self.tableWidgetBilderAktuell.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetBilderAktuell)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidgetBilder = QtGui.QTableWidget(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidgetBilder.setFont(font)
        self.tableWidgetBilder.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidgetBilder.setAcceptDrops(True)
        self.tableWidgetBilder.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetBilder.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.tableWidgetBilder.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetBilder.setIconSize(QtCore.QSize(0, 0))
        self.tableWidgetBilder.setObjectName(_fromUtf8("tableWidgetBilder"))
        self.tableWidgetBilder.setColumnCount(0)
        self.tableWidgetBilder.setRowCount(0)
        self.tableWidgetBilder.horizontalHeader().setDefaultSectionSize(499)
        self.tableWidgetBilder.verticalHeader().setDefaultSectionSize(200)
        self.gridLayout_5.addWidget(self.tableWidgetBilder, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.labelDarsteller = QtGui.QLabel(self.tab_2)
        self.labelDarsteller.setMinimumSize(QtCore.QSize(391, 16))
        self.labelDarsteller.setMaximumSize(QtCore.QSize(391, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDarsteller.setFont(font)
        self.labelDarsteller.setText(_fromUtf8(""))
        self.labelDarsteller.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDarsteller.setObjectName(_fromUtf8("labelDarsteller"))
        self.verticalLayout_12.addWidget(self.labelDarsteller)
        self.frame = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelBildanzeige = QtGui.QLabel(self.frame)
        self.labelBildanzeige.setMinimumSize(QtCore.QSize(0, 0))
        self.labelBildanzeige.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.labelBildanzeige.setAcceptDrops(True)
        self.labelBildanzeige.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelBildanzeige.setText(_fromUtf8(""))
        self.labelBildanzeige.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelBildanzeige.setObjectName(_fromUtf8("labelBildanzeige"))
        self.gridLayout_6.addWidget(self.labelBildanzeige, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(590, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.bildAnzeige = QtGui.QPushButton(self.frame_2)
        self.bildAnzeige.setMinimumSize(QtCore.QSize(24, 24))
        self.bildAnzeige.setMaximumSize(QtCore.QSize(24, 24))
        self.bildAnzeige.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/bild.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bildAnzeige.setIcon(icon3)
        self.bildAnzeige.setIconSize(QtCore.QSize(20, 20))
        self.bildAnzeige.setObjectName(_fromUtf8("bildAnzeige"))
        self.horizontalLayout_7.addWidget(self.bildAnzeige)
        self.comboBoxSex = QtGui.QComboBox(self.frame_2)
        self.comboBoxSex.setMinimumSize(QtCore.QSize(72, 24))
        self.comboBoxSex.setMaximumSize(QtCore.QSize(72, 24))
        self.comboBoxSex.setObjectName(_fromUtf8("comboBoxSex"))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxSex)
        self.pushButtonDarstellerSuchen = QtGui.QPushButton(self.frame_2)
        self.pushButtonDarstellerSuchen.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButtonDarstellerSuchen.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonDarstellerSuchen.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/suchen.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDarstellerSuchen.setIcon(icon4)
        self.pushButtonDarstellerSuchen.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonDarstellerSuchen.setObjectName(_fromUtf8("pushButtonDarstellerSuchen"))
        self.horizontalLayout_7.addWidget(self.pushButtonDarstellerSuchen)
        self.pushButtonUmbenennen = QtGui.QPushButton(self.frame_2)
        self.pushButtonUmbenennen.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButtonUmbenennen.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonUmbenennen.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/umbenennen.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUmbenennen.setIcon(icon5)
        self.pushButtonUmbenennen.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonUmbenennen.setObjectName(_fromUtf8("pushButtonUmbenennen"))
        self.horizontalLayout_7.addWidget(self.pushButtonUmbenennen)
        self.pushButtonDarstellerBild = QtGui.QPushButton(self.frame_2)
        self.pushButtonDarstellerBild.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButtonDarstellerBild.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonDarstellerBild.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/user-identity.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDarstellerBild.setIcon(icon6)
        self.pushButtonDarstellerBild.setObjectName(_fromUtf8("pushButtonDarstellerBild"))
        self.horizontalLayout_7.addWidget(self.pushButtonDarstellerBild)
        self.labelAktiv = QtGui.QLabel(self.frame_2)
        self.labelAktiv.setMinimumSize(QtCore.QSize(70, 0))
        self.labelAktiv.setText(_fromUtf8(""))
        self.labelAktiv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAktiv.setObjectName(_fromUtf8("labelAktiv"))
        self.horizontalLayout_7.addWidget(self.labelAktiv)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelFehler = QtGui.QLabel(self.frame_2)
        self.labelFehler.setMinimumSize(QtCore.QSize(391, 16))
        self.labelFehler.setMaximumSize(QtCore.QSize(391, 16))
        self.labelFehler.setText(_fromUtf8(""))
        self.labelFehler.setObjectName(_fromUtf8("labelFehler"))
        self.gridLayout_2.addWidget(self.labelFehler, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(41, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.labelFilme = QtGui.QLabel(self.frame_2)
        self.labelFilme.setMaximumSize(QtCore.QSize(41, 16))
        self.labelFilme.setWhatsThis(_fromUtf8(""))
        self.labelFilme.setText(_fromUtf8(""))
        self.labelFilme.setObjectName(_fromUtf8("labelFilme"))
        self.gridLayout_2.addWidget(self.labelFilme, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setMinimumSize(QtCore.QSize(41, 16))
        self.label_8.setMaximumSize(QtCore.QSize(41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.labelAlter = QtGui.QLabel(self.frame_2)
        self.labelAlter.setMinimumSize(QtCore.QSize(61, 20))
        self.labelAlter.setMaximumSize(QtCore.QSize(61, 20))
        self.labelAlter.setText(_fromUtf8(""))
        self.labelAlter.setObjectName(_fromUtf8("labelAlter"))
        self.gridLayout_2.addWidget(self.labelAlter, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelText = QtGui.QLabel(self.frame_2)
        self.labelText.setText(_fromUtf8(""))
        self.labelText.setObjectName(_fromUtf8("labelText"))
        self.horizontalLayout_5.addWidget(self.labelText)
        self.comboBoxEthnicFilter = QtGui.QComboBox(self.frame_2)
        self.comboBoxEthnicFilter.setMaximumSize(QtCore.QSize(40, 26))
        self.comboBoxEthnicFilter.setObjectName(_fromUtf8("comboBoxEthnicFilter"))
        self.comboBoxEthnicFilter.addItem(_fromUtf8(""))
        self.comboBoxEthnicFilter.setItemText(0, _fromUtf8(""))
        self.comboBoxEthnicFilter.addItem(_fromUtf8(""))
        self.comboBoxEthnicFilter.addItem(_fromUtf8(""))
        self.comboBoxEthnicFilter.addItem(_fromUtf8(""))
        self.comboBoxEthnicFilter.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBoxEthnicFilter)
        self.comboBoxCSFilter = QtGui.QComboBox(self.frame_2)
        self.comboBoxCSFilter.setMaximumSize(QtCore.QSize(80, 29))
        self.comboBoxCSFilter.setObjectName(_fromUtf8("comboBoxCSFilter"))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.setItemText(0, _fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.comboBoxCSFilter.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBoxCSFilter)
        self.pushButtonSortPartner = QtGui.QPushButton(self.frame_2)
        self.pushButtonSortPartner.setObjectName(_fromUtf8("pushButtonSortPartner"))
        self.horizontalLayout_5.addWidget(self.pushButtonSortPartner)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.listWidgetDarsteller = QtGui.QListWidget(self.frame_2)
        self.listWidgetDarsteller.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidgetDarsteller.setObjectName(_fromUtf8("listWidgetDarsteller"))
        self.verticalLayout_4.addWidget(self.listWidgetDarsteller)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButtonPartnerZeigen = QtGui.QPushButton(self.frame_2)
        self.pushButtonPartnerZeigen.setObjectName(_fromUtf8("pushButtonPartnerZeigen"))
        self.horizontalLayout_6.addWidget(self.pushButtonPartnerZeigen)
        self.pushButtonPseudo = QtGui.QPushButton(self.frame_2)
        self.pushButtonPseudo.setObjectName(_fromUtf8("pushButtonPseudo"))
        self.horizontalLayout_6.addWidget(self.pushButtonPseudo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.listWidgetStatistik = QtGui.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.listWidgetStatistik.setFont(font)
        self.listWidgetStatistik.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidgetStatistik.setObjectName(_fromUtf8("listWidgetStatistik"))
        self.verticalLayout_2.addWidget(self.listWidgetStatistik)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_3.addWidget(self.label_17)
        self.pushButtonSort = QtGui.QPushButton(self.frame_2)
        self.pushButtonSort.setObjectName(_fromUtf8("pushButtonSort"))
        self.horizontalLayout_3.addWidget(self.pushButtonSort)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listWidgetFilme = QtGui.QListWidget(self.frame_2)
        self.listWidgetFilme.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidgetFilme.setObjectName(_fromUtf8("listWidgetFilme"))
        self.verticalLayout_2.addWidget(self.listWidgetFilme)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.comboBoxGeschlecht = QtGui.QComboBox(self.frame_2)
        self.comboBoxGeschlecht.setObjectName(_fromUtf8("comboBoxGeschlecht"))
        self.comboBoxGeschlecht.addItem(_fromUtf8(""))
        self.comboBoxGeschlecht.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBoxGeschlecht)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.lineEditAnzahl = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAnzahl.sizePolicy().hasHeightForWidth())
        self.lineEditAnzahl.setSizePolicy(sizePolicy)
        self.lineEditAnzahl.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lineEditAnzahl.setObjectName(_fromUtf8("lineEditAnzahl"))
        self.horizontalLayout_10.addWidget(self.lineEditAnzahl)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEditGeboren = QtGui.QLineEdit(self.frame_2)
        self.lineEditGeboren.setMaximumSize(QtCore.QSize(98, 16777215))
        self.lineEditGeboren.setObjectName(_fromUtf8("lineEditGeboren"))
        self.horizontalLayout_10.addWidget(self.lineEditGeboren)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.comboBoxHaarfarbe = QtGui.QComboBox(self.frame_2)
        self.comboBoxHaarfarbe.setObjectName(_fromUtf8("comboBoxHaarfarbe"))
        self.comboBoxHaarfarbe.addItem(_fromUtf8(""))
        self.comboBoxHaarfarbe.addItem(_fromUtf8(""))
        self.comboBoxHaarfarbe.addItem(_fromUtf8(""))
        self.comboBoxHaarfarbe.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBoxHaarfarbe)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(45, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_15.addWidget(self.label_4)
        self.comboBoxNation = QtGui.QComboBox(self.frame_2)
        self.comboBoxNation.setObjectName(_fromUtf8("comboBoxNation"))
        self.horizontalLayout_15.addWidget(self.comboBoxNation)
        self.gridLayout.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(45, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.lineEditTattoo = QtGui.QLineEdit(self.frame_2)
        self.lineEditTattoo.setObjectName(_fromUtf8("lineEditTattoo"))
        self.horizontalLayout_12.addWidget(self.lineEditTattoo)
        self.gridLayout.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(45, 18))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBoxEthnic = QtGui.QComboBox(self.frame_2)
        self.comboBoxEthnic.setMaximumSize(QtCore.QSize(40, 26))
        self.comboBoxEthnic.setObjectName(_fromUtf8("comboBoxEthnic"))
        self.comboBoxEthnic.addItem(_fromUtf8(""))
        self.comboBoxEthnic.addItem(_fromUtf8(""))
        self.comboBoxEthnic.addItem(_fromUtf8(""))
        self.comboBoxEthnic.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxEthnic)
        self.pushButtonIAFDholen = QtGui.QPushButton(self.frame_2)
        self.pushButtonIAFDholen.setObjectName(_fromUtf8("pushButtonIAFDholen"))
        self.horizontalLayout.addWidget(self.pushButtonIAFDholen)
        self.pushButtonDarstellerLoeschen = QtGui.QPushButton(self.frame_2)
        self.pushButtonDarstellerLoeschen.setObjectName(_fromUtf8("pushButtonDarstellerLoeschen"))
        self.horizontalLayout.addWidget(self.pushButtonDarstellerLoeschen)
        self.pushButtonDarstellerspeichern = QtGui.QPushButton(self.frame_2)
        self.pushButtonDarstellerspeichern.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonDarstellerspeichern.setObjectName(_fromUtf8("pushButtonDarstellerspeichern"))
        self.horizontalLayout.addWidget(self.pushButtonDarstellerspeichern)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.pushButtonIAFDBackground = QtGui.QPushButton(self.frame_2)
        self.pushButtonIAFDBackground.setObjectName(_fromUtf8("pushButtonIAFDBackground"))
        self.gridLayout.addWidget(self.pushButtonIAFDBackground, 4, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.pushButtonClear = QtGui.QPushButton(self.tab_3)
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.horizontalLayout_20.addWidget(self.pushButtonClear)
        self.lineEditSuchen = QtGui.QLineEdit(self.tab_3)
        self.lineEditSuchen.setObjectName(_fromUtf8("lineEditSuchen"))
        self.horizontalLayout_20.addWidget(self.lineEditSuchen)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_11.addWidget(self.label_18)
        self.lineEditFilesizeFrom = QtGui.QLineEdit(self.tab_3)
        self.lineEditFilesizeFrom.setObjectName(_fromUtf8("lineEditFilesizeFrom"))
        self.horizontalLayout_11.addWidget(self.lineEditFilesizeFrom)
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_11.addWidget(self.label_19)
        self.lineEditFilesizeTo = QtGui.QLineEdit(self.tab_3)
        self.lineEditFilesizeTo.setToolTip(_fromUtf8(""))
        self.lineEditFilesizeTo.setObjectName(_fromUtf8("lineEditFilesizeTo"))
        self.horizontalLayout_11.addWidget(self.lineEditFilesizeTo)
        self.comboBoxFilesizeUnit = QtGui.QComboBox(self.tab_3)
        self.comboBoxFilesizeUnit.setToolTip(_fromUtf8(""))
        self.comboBoxFilesizeUnit.setObjectName(_fromUtf8("comboBoxFilesizeUnit"))
        self.comboBoxFilesizeUnit.addItem(_fromUtf8(""))
        self.comboBoxFilesizeUnit.addItem(_fromUtf8(""))
        self.comboBoxFilesizeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBoxFilesizeUnit)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_11)
        self.pushButtonSuchen = QtGui.QPushButton(self.tab_3)
        self.pushButtonSuchen.setText(_fromUtf8(""))
        self.pushButtonSuchen.setIcon(icon4)
        self.pushButtonSuchen.setObjectName(_fromUtf8("pushButtonSuchen"))
        self.horizontalLayout_20.addWidget(self.pushButtonSuchen)
        self.pushButtonUebernehmen = QtGui.QPushButton(self.tab_3)
        self.pushButtonUebernehmen.setWhatsThis(_fromUtf8(""))
        self.pushButtonUebernehmen.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-up.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pushButtonUebernehmen.setIcon(icon7)
        self.pushButtonUebernehmen.setObjectName(_fromUtf8("pushButtonUebernehmen"))
        self.horizontalLayout_20.addWidget(self.pushButtonUebernehmen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.labelMpgGefunden = QtGui.QLabel(self.groupBox_2)
        self.labelMpgGefunden.setMinimumSize(QtCore.QSize(126, 14))
        self.labelMpgGefunden.setObjectName(_fromUtf8("labelMpgGefunden"))
        self.horizontalLayout_21.addWidget(self.labelMpgGefunden)
        self.lineEditSearchMpg = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditSearchMpg.setObjectName(_fromUtf8("lineEditSearchMpg"))
        self.horizontalLayout_21.addWidget(self.lineEditSearchMpg)
        self.pushButtonSearchMpg = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonSearchMpg.setText(_fromUtf8(""))
        self.pushButtonSearchMpg.setIcon(icon4)
        self.pushButtonSearchMpg.setObjectName(_fromUtf8("pushButtonSearchMpg"))
        self.horizontalLayout_21.addWidget(self.pushButtonSearchMpg)
        self.labelMpgFound = QtGui.QLabel(self.groupBox_2)
        self.labelMpgFound.setText(_fromUtf8(""))
        self.labelMpgFound.setObjectName(_fromUtf8("labelMpgFound"))
        self.horizontalLayout_21.addWidget(self.labelMpgFound)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.gridLayout_7.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget.setToolTip(_fromUtf8(""))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.labelVidGefunden = QtGui.QLabel(self.groupBox_3)
        self.labelVidGefunden.setMinimumSize(QtCore.QSize(126, 0))
        self.labelVidGefunden.setMaximumSize(QtCore.QSize(140, 16777215))
        self.labelVidGefunden.setObjectName(_fromUtf8("labelVidGefunden"))
        self.horizontalLayout_22.addWidget(self.labelVidGefunden)
        self.lineEditSearchVid = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditSearchVid.setObjectName(_fromUtf8("lineEditSearchVid"))
        self.horizontalLayout_22.addWidget(self.lineEditSearchVid)
        self.pushButtonSearchVid = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonSearchVid.setText(_fromUtf8(""))
        self.pushButtonSearchVid.setIcon(icon4)
        self.pushButtonSearchVid.setObjectName(_fromUtf8("pushButtonSearchVid"))
        self.horizontalLayout_22.addWidget(self.pushButtonSearchVid)
        self.labelVidFound = QtGui.QLabel(self.groupBox_3)
        self.labelVidFound.setText(_fromUtf8(""))
        self.labelVidFound.setObjectName(_fromUtf8("labelVidFound"))
        self.horizontalLayout_22.addWidget(self.labelVidFound)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.tableWidget1 = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget1.setToolTip(_fromUtf8(""))
        self.tableWidget1.setObjectName(_fromUtf8("tableWidget1"))
        self.tableWidget1.setColumnCount(0)
        self.tableWidget1.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidget1, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButtonBack = QtGui.QPushButton(self.tab_4)
        self.pushButtonBack.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-previous.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon8)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.horizontalLayout_14.addWidget(self.pushButtonBack)
        self.pushButtonForward = QtGui.QPushButton(self.tab_4)
        self.pushButtonForward.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-next.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForward.setIcon(icon9)
        self.pushButtonForward.setObjectName(_fromUtf8("pushButtonForward"))
        self.horizontalLayout_14.addWidget(self.pushButtonForward)
        self.pushButtonIAFD = QtGui.QPushButton(self.tab_4)
        self.pushButtonIAFD.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/favicon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonIAFD.setIcon(icon10)
        self.pushButtonIAFD.setObjectName(_fromUtf8("pushButtonIAFD"))
        self.horizontalLayout_14.addWidget(self.pushButtonIAFD)
        self.lineEditSearchWebsite = QtGui.QLineEdit(self.tab_4)
        self.lineEditSearchWebsite.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearchWebsite.setObjectName(_fromUtf8("lineEditSearchWebsite"))
        self.horizontalLayout_14.addWidget(self.lineEditSearchWebsite)
        self.pushButtonSearchWebsite = QtGui.QPushButton(self.tab_4)
        self.pushButtonSearchWebsite.setText(_fromUtf8(""))
        self.pushButtonSearchWebsite.setIcon(icon4)
        self.pushButtonSearchWebsite.setObjectName(_fromUtf8("pushButtonSearchWebsite"))
        self.horizontalLayout_14.addWidget(self.pushButtonSearchWebsite)
        self.pushButtonVideo = QtGui.QPushButton(self.tab_4)
        self.pushButtonVideo.setObjectName(_fromUtf8("pushButtonVideo"))
        self.horizontalLayout_14.addWidget(self.pushButtonVideo)
        self.pushButtonAbholen = QtGui.QPushButton(self.tab_4)
        self.pushButtonAbholen.setObjectName(_fromUtf8("pushButtonAbholen"))
        self.horizontalLayout_14.addWidget(self.pushButtonAbholen)
        self.pushButtonMovie = QtGui.QPushButton(self.tab_4)
        self.pushButtonMovie.setObjectName(_fromUtf8("pushButtonMovie"))
        self.horizontalLayout_14.addWidget(self.pushButtonMovie)
        self.lineEditURL = QtGui.QLineEdit(self.tab_4)
        self.lineEditURL.setObjectName(_fromUtf8("lineEditURL"))
        self.horizontalLayout_14.addWidget(self.lineEditURL)
        self.pushButtonUrl = QtGui.QPushButton(self.tab_4)
        self.pushButtonUrl.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/bookmarks.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUrl.setIcon(icon11)
        self.pushButtonUrl.setObjectName(_fromUtf8("pushButtonUrl"))
        self.horizontalLayout_14.addWidget(self.pushButtonUrl)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.webView = QtWebKit.QWebView(self.tab_4)
        self.webView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_10.addWidget(self.webView)
        self.gridLayout_10.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.tableWidgetStatistik = QtGui.QTableWidget(self.tab_5)
        self.tableWidgetStatistik.setObjectName(_fromUtf8("tableWidgetStatistik"))
        self.tableWidgetStatistik.setColumnCount(0)
        self.tableWidgetStatistik.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.tableWidgetStatistik)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButtonCS = QtGui.QPushButton(self.tab_5)
        self.pushButtonCS.setObjectName(_fromUtf8("pushButtonCS"))
        self.verticalLayout_11.addWidget(self.pushButtonCS)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.pushButtonDarstellerW = QtGui.QPushButton(self.tab_5)
        self.pushButtonDarstellerW.setObjectName(_fromUtf8("pushButtonDarstellerW"))
        self.horizontalLayout_17.addWidget(self.pushButtonDarstellerW)
        self.lineEditAnzahlW = QtGui.QLineEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAnzahlW.sizePolicy().hasHeightForWidth())
        self.lineEditAnzahlW.setSizePolicy(sizePolicy)
        self.lineEditAnzahlW.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lineEditAnzahlW.setMaxLength(4)
        self.lineEditAnzahlW.setObjectName(_fromUtf8("lineEditAnzahlW"))
        self.horizontalLayout_17.addWidget(self.lineEditAnzahlW)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtonDarstellerM = QtGui.QPushButton(self.tab_5)
        self.pushButtonDarstellerM.setObjectName(_fromUtf8("pushButtonDarstellerM"))
        self.horizontalLayout_8.addWidget(self.pushButtonDarstellerM)
        self.lineEditAnzahlM = QtGui.QLineEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAnzahlM.sizePolicy().hasHeightForWidth())
        self.lineEditAnzahlM.setSizePolicy(sizePolicy)
        self.lineEditAnzahlM.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lineEditAnzahlM.setMaxLength(4)
        self.lineEditAnzahlM.setObjectName(_fromUtf8("lineEditAnzahlM"))
        self.horizontalLayout_8.addWidget(self.lineEditAnzahlM)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.pushButtonAnzahlClips = QtGui.QPushButton(self.tab_5)
        self.pushButtonAnzahlClips.setObjectName(_fromUtf8("pushButtonAnzahlClips"))
        self.verticalLayout_11.addWidget(self.pushButtonAnzahlClips)
        self.pushButtonClipsJahr = QtGui.QPushButton(self.tab_5)
        self.pushButtonClipsJahr.setObjectName(_fromUtf8("pushButtonClipsJahr"))
        self.verticalLayout_11.addWidget(self.pushButtonClipsJahr)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.gridLayout_11.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.checkBoxPictures = QtGui.QCheckBox(self.tab_6)
        self.checkBoxPictures.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBoxPictures.setChecked(True)
        self.checkBoxPictures.setObjectName(_fromUtf8("checkBoxPictures"))
        self.gridLayout_14.addWidget(self.checkBoxPictures, 0, 2, 1, 1)
        self.pushButtonBackup = QtGui.QPushButton(self.tab_6)
        self.pushButtonBackup.setObjectName(_fromUtf8("pushButtonBackup"))
        self.gridLayout_14.addWidget(self.pushButtonBackup, 0, 0, 1, 1)
        self.pushButtonRestore = QtGui.QPushButton(self.tab_6)
        self.pushButtonRestore.setObjectName(_fromUtf8("pushButtonRestore"))
        self.gridLayout_14.addWidget(self.pushButtonRestore, 1, 0, 1, 1)
        self.pushButtonWartung = QtGui.QPushButton(self.tab_6)
        self.pushButtonWartung.setObjectName(_fromUtf8("pushButtonWartung"))
        self.gridLayout_14.addWidget(self.pushButtonWartung, 2, 0, 1, 1)
        self.pushButtonDateikatalog = QtGui.QPushButton(self.tab_6)
        self.pushButtonDateikatalog.setCheckable(True)
        self.pushButtonDateikatalog.setObjectName(_fromUtf8("pushButtonDateikatalog"))
        self.gridLayout_14.addWidget(self.pushButtonDateikatalog, 3, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_14.addWidget(self.label_12, 2, 3, 1, 1)
        self.checkBoxDatabase = QtGui.QCheckBox(self.tab_6)
        self.checkBoxDatabase.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBoxDatabase.setChecked(True)
        self.checkBoxDatabase.setObjectName(_fromUtf8("checkBoxDatabase"))
        self.gridLayout_14.addWidget(self.checkBoxDatabase, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_14.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_14.addWidget(self.label_13, 3, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_14.addWidget(self.label_10, 0, 3, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_14)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.frame_Dateikatalog = QtGui.QFrame(self.tab_6)
        self.frame_Dateikatalog.setMinimumSize(QtCore.QSize(200, 200))
        self.frame_Dateikatalog.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Dateikatalog.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Dateikatalog.setObjectName(_fromUtf8("frame_Dateikatalog"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_Dateikatalog)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.frame_Dateikatalog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.comboBoxDevice = QtGui.QComboBox(self.frame_Dateikatalog)
        self.comboBoxDevice.setObjectName(_fromUtf8("comboBoxDevice"))
        self.horizontalLayout_16.addWidget(self.comboBoxDevice)
        self.pushButtonVerwalten = QtGui.QPushButton(self.frame_Dateikatalog)
        self.pushButtonVerwalten.setToolTip(_fromUtf8(""))
        self.pushButtonVerwalten.setObjectName(_fromUtf8("pushButtonVerwalten"))
        self.horizontalLayout_16.addWidget(self.pushButtonVerwalten)
        self.pushButtonStart = QtGui.QPushButton(self.frame_Dateikatalog)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.horizontalLayout_16.addWidget(self.pushButtonStart)
        spacerItem3 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.line = QtGui.QFrame(self.frame_Dateikatalog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_13.addWidget(self.line)
        self.label_15 = QtGui.QLabel(self.frame_Dateikatalog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_13.addWidget(self.label_15)
        self.tableWidgetDubletten = QtGui.QTableWidget(self.frame_Dateikatalog)
        self.tableWidgetDubletten.setObjectName(_fromUtf8("tableWidgetDubletten"))
        self.tableWidgetDubletten.setColumnCount(0)
        self.tableWidgetDubletten.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableWidgetDubletten)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pushButtonDeleteDuplicates = QtGui.QPushButton(self.frame_Dateikatalog)
        self.pushButtonDeleteDuplicates.setObjectName(_fromUtf8("pushButtonDeleteDuplicates"))
        self.horizontalLayout_18.addWidget(self.pushButtonDeleteDuplicates)
        self.pushButtonDeselect = QtGui.QPushButton(self.frame_Dateikatalog)
        self.pushButtonDeselect.setObjectName(_fromUtf8("pushButtonDeselect"))
        self.horizontalLayout_18.addWidget(self.pushButtonDeselect)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.gridLayout_15.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_Dateikatalog)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.gridLayout_16.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDarsteller = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/darsteller.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDarsteller.setIcon(icon12)
        self.actionDarsteller.setObjectName(_fromUtf8("actionDarsteller"))
        self.actionCd = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/cd.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCd.setIcon(icon13)
        self.actionCd.setObjectName(_fromUtf8("actionCd"))
        self.actionTitel = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/titel.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTitel.setIcon(icon14)
        self.actionTitel.setObjectName(_fromUtf8("actionTitel"))
        self.actionOriginal = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/original.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOriginal.setIcon(icon15)
        self.actionOriginal.setObjectName(_fromUtf8("actionOriginal"))
        self.actionVid = QtGui.QAction(MainWindow)
        self.actionVid.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVid.setIcon(icon16)
        self.actionVid.setObjectName(_fromUtf8("actionVid"))
        self.actionCheckBoxDVDCover = QtGui.QAction(MainWindow)
        self.actionCheckBoxDVDCover.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/dvd_unmount.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckBoxDVDCover.setIcon(icon17)
        self.actionCheckBoxDVDCover.setObjectName(_fromUtf8("actionCheckBoxDVDCover"))
        self.actionSuche = QtGui.QAction(MainWindow)
        self.actionSuche.setIcon(icon4)
        self.actionSuche.setObjectName(_fromUtf8("actionSuche"))
        self.actionDrucken = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/printer1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrucken.setIcon(icon18)
        self.actionDrucken.setObjectName(_fromUtf8("actionDrucken"))
        self.actionSuchfeld = QtGui.QAction(MainWindow)
        self.actionSuchfeld.setObjectName(_fromUtf8("actionSuchfeld"))
        self.actionSuchbegriffe = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/kdict.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuchbegriffe.setIcon(icon19)
        self.actionSuchbegriffe.setObjectName(_fromUtf8("actionSuchbegriffe"))
        self.actionLand = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/land.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLand.setIcon(icon20)
        self.actionLand.setObjectName(_fromUtf8("actionLand"))
        self.actionFirst = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-first.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirst.setIcon(icon21)
        self.actionFirst.setObjectName(_fromUtf8("actionFirst"))
        self.actionPrev = QtGui.QAction(MainWindow)
        self.actionPrev.setIcon(icon8)
        self.actionPrev.setObjectName(_fromUtf8("actionPrev"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setIcon(icon9)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionLast = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-last.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLast.setIcon(icon22)
        self.actionLast.setObjectName(_fromUtf8("actionLast"))
        self.actionAnzahlBilder = QtGui.QAction(MainWindow)
        self.actionAnzahlBilder.setObjectName(_fromUtf8("actionAnzahlBilder"))
        self.actionUndo = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/undo.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon23)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionDarstellerUebernehmen = QtGui.QAction(MainWindow)
        self.actionDarstellerUebernehmen.setObjectName(_fromUtf8("actionDarstellerUebernehmen"))
        self.actionAnzeigenOriginal = QtGui.QAction(MainWindow)
        self.actionAnzeigenOriginal.setObjectName(_fromUtf8("actionAnzeigenOriginal"))
        self.actionSortieren_nach_Darsteller = QtGui.QAction(MainWindow)
        self.actionSortieren_nach_Darsteller.setObjectName(_fromUtf8("actionSortieren_nach_Darsteller"))
        self.actionSortieren_nach_CD = QtGui.QAction(MainWindow)
        self.actionSortieren_nach_CD.setObjectName(_fromUtf8("actionSortieren_nach_CD"))
        self.actionSortieren_nach_Titel = QtGui.QAction(MainWindow)
        self.actionSortieren_nach_Titel.setObjectName(_fromUtf8("actionSortieren_nach_Titel"))
        self.actionOriginal_umbenennen = QtGui.QAction(MainWindow)
        self.actionOriginal_umbenennen.setObjectName(_fromUtf8("actionOriginal_umbenennen"))
        self.actionOriginal_weitere = QtGui.QAction(MainWindow)
        self.actionOriginal_weitere.setObjectName(_fromUtf8("actionOriginal_weitere"))
        self.actionSortieren_nach_Original = QtGui.QAction(MainWindow)
        self.actionSortieren_nach_Original.setObjectName(_fromUtf8("actionSortieren_nach_Original"))
        self.actionCovergross = QtGui.QAction(MainWindow)
        self.actionCovergross.setObjectName(_fromUtf8("actionCovergross"))
        self.actionBildLoeschen = QtGui.QAction(MainWindow)
        self.actionBildLoeschen.setObjectName(_fromUtf8("actionBildLoeschen"))
        self.actionAnzeigenPaar = QtGui.QAction(MainWindow)
        self.actionAnzeigenPaar.setObjectName(_fromUtf8("actionAnzeigenPaar"))
        self.actionBildanzeigegross = QtGui.QAction(MainWindow)
        self.actionBildanzeigegross.setObjectName(_fromUtf8("actionBildanzeigegross"))
        self.actionFilm_zeigen = QtGui.QAction(MainWindow)
        self.actionFilm_zeigen.setObjectName(_fromUtf8("actionFilm_zeigen"))
        self.actionCSZeigen = QtGui.QAction(MainWindow)
        self.actionCSZeigen.setObjectName(_fromUtf8("actionCSZeigen"))
        self.actionNeueingabe = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeueingabe.setIcon(icon24)
        self.actionNeueingabe.setObjectName(_fromUtf8("actionNeueingabe"))
        self.actionOnHelp = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/dialog-information.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOnHelp.setIcon(icon25)
        self.actionOnHelp.setObjectName(_fromUtf8("actionOnHelp"))
        self.actionOriginalIntoClipboard = QtGui.QAction(MainWindow)
        self.actionOriginalIntoClipboard.setObjectName(_fromUtf8("actionOriginalIntoClipboard"))
        self.actionRedoImageChange = QtGui.QAction(MainWindow)
        self.actionRedoImageChange.setObjectName(_fromUtf8("actionRedoImageChange"))
        self.actionGetUrl = QtGui.QAction(MainWindow)
        self.actionGetUrl.setObjectName(_fromUtf8("actionGetUrl"))
        self.actionGoToUrl = QtGui.QAction(MainWindow)
        self.actionGoToUrl.setObjectName(_fromUtf8("actionGoToUrl"))
        self.actionAnzeigenTitle = QtGui.QAction(MainWindow)
        self.actionAnzeigenTitle.setObjectName(_fromUtf8("actionAnzeigenTitle"))
        self.actionShowDetails = QtGui.QAction(MainWindow)
        self.actionShowDetails.setObjectName(_fromUtf8("actionShowDetails"))
        self.toolBar.addAction(self.actionNeueingabe)
        self.toolBar.addAction(self.actionSuchfeld)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDarsteller)
        self.toolBar.addAction(self.actionCd)
        self.toolBar.addAction(self.actionTitel)
        self.toolBar.addAction(self.actionOriginal)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVid)
        self.toolBar.addAction(self.actionCheckBoxDVDCover)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSuche)
        self.toolBar.addAction(self.actionDrucken)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFirst)
        self.toolBar.addAction(self.actionPrev)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionLast)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSuchbegriffe)
        self.toolBar.addAction(self.actionLand)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAnzahlBilder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOnHelp)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_akt_verzeichnis.setToolTip(_translate("MainWindow", "act. directory", None))
        self.label_akt_verzeichnis.setWhatsThis(_translate("MainWindow", "Actual directory", None))
        self.label_akt_verzeichnis.setText(_translate("MainWindow", "act. directory", None))
        self.pushButtonRefresh.setToolTip(_translate("MainWindow", "Refresh view or working directory", None))
        self.pushButtonRefresh.setWhatsThis(_translate("MainWindow", "Sometimes it happens that the automatically refresh does not work. With this button you can force a refresh.", None))
        self.pushButtonDir.setToolTip(_translate("MainWindow", "Change directory", None))
        self.pushButtonDir.setWhatsThis(_translate("MainWindow", "Change actual directory.", None))
        self.tableWidgetBilderAktuell.setWhatsThis(_translate("MainWindow", "Actual image files in working directory. For adding the image file to the database, double click on it or mark it and press F5. If 2 image files are marked, the dialog for adding a cover will appear.", None))
        self.tableWidgetBilder.setWhatsThis(_translate("MainWindow", "Presentation of the search result. A contextual menu appears when you right click on any item. By double clicking on an item it can be changed or deleted in mode of viewing clips or the actors data will be shown in mode of viewing actors. In mode of viewing clips F12 toggles showing complete data (title and image file) or not.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Images", None))
        self.labelBildanzeige.setWhatsThis(_translate("MainWindow", "Image of the actor", None))
        self.bildAnzeige.setToolTip(_translate("MainWindow", "Show actor and search for actors\n"
"Ctrl+B", None))
        self.bildAnzeige.setWhatsThis(_translate("MainWindow", "The most significant button: shows all information of the actor", None))
        self.comboBoxSex.setToolTip(_translate("MainWindow", "Gender", None))
        self.comboBoxSex.setWhatsThis(_translate("MainWindow", "Filter selection for gender", None))
        self.comboBoxSex.setItemText(0, _translate("MainWindow", "whatever", None))
        self.comboBoxSex.setItemText(1, _translate("MainWindow", "Male", None))
        self.comboBoxSex.setItemText(2, _translate("MainWindow", "Female", None))
        self.pushButtonDarstellerSuchen.setToolTip(_translate("MainWindow", "Search actor, Ctrl+shift+F", None))
        self.pushButtonDarstellerSuchen.setWhatsThis(_translate("MainWindow", "Search for actors", None))
        self.pushButtonDarstellerSuchen.setShortcut(_translate("MainWindow", "Ctrl+Shift+F", None))
        self.pushButtonUmbenennen.setToolTip(_translate("MainWindow", "Rename actor, Ctrl+U", None))
        self.pushButtonUmbenennen.setWhatsThis(_translate("MainWindow", "Rename actor", None))
        self.pushButtonUmbenennen.setShortcut(_translate("MainWindow", "Ctrl+U", None))
        self.pushButtonDarstellerBild.setToolTip(_translate("MainWindow", "Adopt new image of the actor, Ctrl+J", None))
        self.pushButtonDarstellerBild.setWhatsThis(_translate("MainWindow", "Replace existing image of the actor with a new one", None))
        self.pushButtonDarstellerBild.setShortcut(_translate("MainWindow", "Ctrl+J", None))
        self.labelAktiv.setToolTip(_translate("MainWindow", "<html><head/><body><p>Active from ... to according IAFD and last visit of IAFD with this actor</p></body></html>", None))
        self.labelAktiv.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "Movies:", None))
        self.labelFilme.setToolTip(_translate("MainWindow", "<html><head/><body><p>Films according to the IAFD</p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "Age:", None))
        self.comboBoxEthnicFilter.setToolTip(_translate("MainWindow", "Filter on ethnic", None))
        self.comboBoxEthnicFilter.setWhatsThis(_translate("MainWindow", "Filter partners on ethnic", None))
        self.comboBoxEthnicFilter.setItemText(1, _translate("MainWindow", "w", None))
        self.comboBoxEthnicFilter.setItemText(2, _translate("MainWindow", "a", None))
        self.comboBoxEthnicFilter.setItemText(3, _translate("MainWindow", "s", None))
        self.comboBoxEthnicFilter.setItemText(4, _translate("MainWindow", "l", None))
        self.comboBoxCSFilter.setToolTip(_translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Filter on cumshot</p></body></html>", None))
        self.comboBoxCSFilter.setWhatsThis(_translate("MainWindow", "Filter on cumshot", None))
        self.comboBoxCSFilter.setItemText(1, _translate("MainWindow", "f Facial", None))
        self.comboBoxCSFilter.setItemText(2, _translate("MainWindow", "h Handjob", None))
        self.comboBoxCSFilter.setItemText(3, _translate("MainWindow", "t Tits", None))
        self.comboBoxCSFilter.setItemText(4, _translate("MainWindow", "c Creampie", None))
        self.comboBoxCSFilter.setItemText(5, _translate("MainWindow", "x Analcreampie", None))
        self.comboBoxCSFilter.setItemText(6, _translate("MainWindow", "o Oralcreampie", None))
        self.comboBoxCSFilter.setItemText(7, _translate("MainWindow", "v Cunt", None))
        self.comboBoxCSFilter.setItemText(8, _translate("MainWindow", "b Belly", None))
        self.comboBoxCSFilter.setItemText(9, _translate("MainWindow", "a Ass", None))
        self.comboBoxCSFilter.setItemText(10, _translate("MainWindow", "s Others", None))
        self.pushButtonSortPartner.setToolTip(_translate("MainWindow", "Sort on ...", None))
        self.pushButtonSortPartner.setText(_translate("MainWindow", "Quantity", None))
        self.listWidgetDarsteller.setWhatsThis(_translate("MainWindow", "Has acted with", None))
        self.pushButtonPartnerZeigen.setToolTip(_translate("MainWindow", "Show partners", None))
        self.pushButtonPartnerZeigen.setWhatsThis(_translate("MainWindow", "Show actors in first tab", None))
        self.pushButtonPartnerZeigen.setText(_translate("MainWindow", "Show actors", None))
        self.pushButtonPseudo.setWhatsThis(_translate("MainWindow", "Add alias", None))
        self.pushButtonPseudo.setText(_translate("MainWindow", "Alias", None))
        self.label_16.setText(_translate("MainWindow", "Cumshots:", None))
        self.listWidgetStatistik.setWhatsThis(_translate("MainWindow", "Cumshot statistic", None))
        self.label_17.setText(_translate("MainWindow", "Films:", None))
        self.pushButtonSort.setToolTip(_translate("MainWindow", "Sort on ...", None))
        self.pushButtonSort.setWhatsThis(_translate("MainWindow", "Sort alphabetically or on year", None))
        self.pushButtonSort.setText(_translate("MainWindow", "Year", None))
        self.listWidgetFilme.setWhatsThis(_translate("MainWindow", "Movies with this actor in the database", None))
        self.label.setText(_translate("MainWindow", "Gender", None))
        self.comboBoxGeschlecht.setItemText(0, _translate("MainWindow", "w", None))
        self.comboBoxGeschlecht.setItemText(1, _translate("MainWindow", "m", None))
        self.label_2.setText(_translate("MainWindow", "Quantity", None))
        self.lineEditAnzahl.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Quantity of films in the PorDB</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Born", None))
        self.label_3.setText(_translate("MainWindow", "Hair color", None))
        self.comboBoxHaarfarbe.setItemText(0, _translate("MainWindow", "bl", None))
        self.comboBoxHaarfarbe.setItemText(1, _translate("MainWindow", "br", None))
        self.comboBoxHaarfarbe.setItemText(2, _translate("MainWindow", "r", None))
        self.comboBoxHaarfarbe.setItemText(3, _translate("MainWindow", "s", None))
        self.label_4.setText(_translate("MainWindow", "Nation", None))
        self.label_5.setText(_translate("MainWindow", "Tattoo", None))
        self.label_6.setText(_translate("MainWindow", "Ethnic", None))
        self.comboBoxEthnic.setItemText(0, _translate("MainWindow", "w", None))
        self.comboBoxEthnic.setItemText(1, _translate("MainWindow", "a", None))
        self.comboBoxEthnic.setItemText(2, _translate("MainWindow", "s", None))
        self.comboBoxEthnic.setItemText(3, _translate("MainWindow", "l", None))
        self.pushButtonIAFDholen.setToolTip(_translate("MainWindow", "Get actors information from the IAFD, Ctrl+I", None))
        self.pushButtonIAFDholen.setText(_translate("MainWindow", "Get data from the IAFD", None))
        self.pushButtonIAFDholen.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.pushButtonDarstellerLoeschen.setToolTip(_translate("MainWindow", "Delete all information from this actor inclusive the image, Ctrl+L", None))
        self.pushButtonDarstellerLoeschen.setText(_translate("MainWindow", "Delete actor", None))
        self.pushButtonDarstellerLoeschen.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.pushButtonDarstellerspeichern.setToolTip(_translate("MainWindow", "Save changes, Ctrl+S", None))
        self.pushButtonDarstellerspeichern.setWhatsThis(_translate("MainWindow", "Save actor data", None))
        self.pushButtonDarstellerspeichern.setText(_translate("MainWindow", "Save", None))
        self.pushButtonDarstellerspeichern.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.pushButtonIAFDBackground.setToolTip(_translate("MainWindow", "Update actors data from the IAFD, Ctrl+shift+A", None))
        self.pushButtonIAFDBackground.setText(_translate("MainWindow", "Update data from the IAFD", None))
        self.pushButtonIAFDBackground.setShortcut(_translate("MainWindow", "Ctrl+Shift+A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Actors", None))
        self.pushButtonClear.setToolTip(_translate("MainWindow", "Strg+L", None))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear search field", None))
        self.pushButtonClear.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.lineEditSuchen.setWhatsThis(_translate("MainWindow", "Search field", None))
        self.label_18.setText(_translate("MainWindow", "File size:", None))
        self.lineEditFilesizeFrom.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Enter file size here. You can enter a single file size, or a range. Select the unit from the combobox in the right.</p><p><br/></p><p>When something is entered in the search field on the left, it is combined with the size field with &quot;and&quot;. </p></body></html>", None))
        self.label_19.setText(_translate("MainWindow", "-", None))
        self.lineEditFilesizeTo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Enter file size here. You can enter a single file size, or a range. Select the unit from the combobox in the right.</p><p><br/>When something is entered in the search field on the left, it is combined with the size field with &quot;and&quot;. </p></body></html>", None))
        self.comboBoxFilesizeUnit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Select the unit for the file size.</p><p><br/></p><p>MB = Megabyte</p><p>GB = Gigabyte</p></body></html>", None))
        self.comboBoxFilesizeUnit.setItemText(0, _translate("MainWindow", "MB", None))
        self.comboBoxFilesizeUnit.setItemText(1, _translate("MainWindow", "GB", None))
        self.comboBoxFilesizeUnit.setItemText(2, _translate("MainWindow", "Bytes", None))
        self.pushButtonSuchen.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Execute search, Enter</p></body></html>", None))
        self.pushButtonSuchen.setShortcut(_translate("MainWindow", "Return", None))
        self.pushButtonUebernehmen.setToolTip(_translate("MainWindow", "<html><head/><body><p>Copy content from this search field to the main search field, Ctrl+PageUp</p></body></html>", None))
        self.pushButtonUebernehmen.setShortcut(_translate("MainWindow", "Ctrl+PgUp", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "mpg_katalog", None))
        self.labelMpgGefunden.setText(_translate("MainWindow", "0 found", None))
        self.pushButtonSearchMpg.setWhatsThis(_translate("MainWindow", "Search in results", None))
        self.tableWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Search result from file catalog</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Vid", None))
        self.labelVidGefunden.setText(_translate("MainWindow", "0 found", None))
        self.pushButtonSearchVid.setToolTip(_translate("MainWindow", "Search in results", None))
        self.tableWidget1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Search result from database</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Search file", None))
        self.pushButtonBack.setToolTip(_translate("MainWindow", "back", None))
        self.pushButtonForward.setToolTip(_translate("MainWindow", "forward", None))
        self.pushButtonIAFD.setToolTip(_translate("MainWindow", "Load IAFD site", None))
        self.pushButtonIAFD.setWhatsThis(_translate("MainWindow", "Load IAFD site", None))
        self.lineEditSearchWebsite.setWhatsThis(_translate("MainWindow", "Enter text to search in website", None))
        self.pushButtonSearchWebsite.setToolTip(_translate("MainWindow", "Search in website, Ctrl+shift+F", None))
        self.pushButtonSearchWebsite.setShortcut(_translate("MainWindow", "Ctrl+Shift+F", None))
        self.pushButtonVideo.setWhatsThis(_translate("MainWindow", "Check which movies are in database.", None))
        self.pushButtonVideo.setText(_translate("MainWindow", "Movies available?", None))
        self.pushButtonVideo.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.pushButtonAbholen.setWhatsThis(_translate("MainWindow", "Adopt actors data from the IAFD.", None))
        self.pushButtonAbholen.setText(_translate("MainWindow", "Get actor data", None))
        self.pushButtonMovie.setWhatsThis(_translate("MainWindow", "Adopt movie data from the IAFD.\n"
"\n"
"This is very useful for adding new scenes from the selected movie.", None))
        self.pushButtonMovie.setText(_translate("MainWindow", "Enter clips for shown video", None))
        self.lineEditURL.setWhatsThis(_translate("MainWindow", "Adress bar", None))
        self.pushButtonUrl.setToolTip(_translate("MainWindow", "Bookmarks", None))
        self.pushButtonUrl.setWhatsThis(_translate("MainWindow", "Maintenance of bookmarks", None))
        self.webView.setWhatsThis(_translate("MainWindow", "Web content, controls:\n"
"Back: Z\n"
"Forward: X\n"
"Stop: S", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Search on IAFD", None))
        self.tableWidgetStatistik.setWhatsThis(_translate("MainWindow", "Statistics", None))
        self.pushButtonCS.setToolTip(_translate("MainWindow", "Cumshot statistic", None))
        self.pushButtonCS.setWhatsThis(_translate("MainWindow", "Cumshot statistic", None))
        self.pushButtonCS.setText(_translate("MainWindow", "CumShots", None))
        self.pushButtonDarstellerW.setWhatsThis(_translate("MainWindow", "Female actors statistics ", None))
        self.pushButtonDarstellerW.setText(_translate("MainWindow", "Actors female", None))
        self.lineEditAnzahlW.setToolTip(_translate("MainWindow", "Filter on quantity partners", None))
        self.lineEditAnzahlW.setWhatsThis(_translate("MainWindow", "Show female actors with more than ... partners", None))
        self.pushButtonDarstellerM.setWhatsThis(_translate("MainWindow", "Male actors statistics ", None))
        self.pushButtonDarstellerM.setText(_translate("MainWindow", "Actors male", None))
        self.lineEditAnzahlM.setToolTip(_translate("MainWindow", "Filter on quantity partners", None))
        self.lineEditAnzahlM.setWhatsThis(_translate("MainWindow", "Show male actors with more than ... partners", None))
        self.pushButtonAnzahlClips.setToolTip(_translate("MainWindow", "Show quantity of movies", None))
        self.pushButtonAnzahlClips.setText(_translate("MainWindow", "Quantity of movies", None))
        self.pushButtonClipsJahr.setWhatsThis(_translate("MainWindow", "Show quantity of movies per year", None))
        self.pushButtonClipsJahr.setText(_translate("MainWindow", "Movies / year", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Statistics", None))
        self.checkBoxPictures.setToolTip(_translate("MainWindow", "<html><head/><body><p>When checked: Backup of the picture directory</p></body></html>", None))
        self.checkBoxPictures.setText(_translate("MainWindow", "Pictures", None))
        self.pushButtonBackup.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Database will be unloaded and saved in the working directory. This files can be saved on e. g. external devices. That is also helpful for moving on a new computer. With the reload button the database can be reloaded</p></body></html>", None))
        self.pushButtonBackup.setText(_translate("MainWindow", "Backup", None))
        self.pushButtonRestore.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Restore database.</p></body></html>", None))
        self.pushButtonRestore.setText(_translate("MainWindow", "Restore", None))
        self.pushButtonWartung.setText(_translate("MainWindow", "Maintenance", None))
        self.pushButtonDateikatalog.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scan a file directory for video files. Filenames are entered in the database and can be searched (Tab &quot;Search files&quot;).</p></body></html>", None))
        self.pushButtonDateikatalog.setText(_translate("MainWindow", "File catalogue", None))
        self.label_12.setText(_translate("MainWindow", "Maintenance of the database: especially free memory and analyze", None))
        self.checkBoxDatabase.setToolTip(_translate("MainWindow", "<html><head/><body><p>When checked: Backup of the database entries</p></body></html>", None))
        self.checkBoxDatabase.setText(_translate("MainWindow", "Database", None))
        self.label_11.setText(_translate("MainWindow", "Restore database", None))
        self.label_13.setText(_translate("MainWindow", "Collect video files from a directory", None))
        self.label_10.setText(_translate("MainWindow", "Backup of the database into the working directory", None))
        self.label_14.setText(_translate("MainWindow", "Devicename:", None))
        self.comboBoxDevice.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a device name. Device names must be unambiguous .</p></body></html>", None))
        self.pushButtonVerwalten.setText(_translate("MainWindow", "Maintain device names", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start", None))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#800080;\">This table will show possible duplicates:</span></p></body></html>", None))
        self.tableWidgetDubletten.setSortingEnabled(True)
        self.pushButtonDeleteDuplicates.setToolTip(_translate("MainWindow", "All checked files and entries in database will be deleted, Ctrl+L", None))
        self.pushButtonDeleteDuplicates.setText(_translate("MainWindow", "Delete duplicates", None))
        self.pushButtonDeleteDuplicates.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.pushButtonDeselect.setToolTip(_translate("MainWindow", "Deselect all marked lines, Ctrl+A", None))
        self.pushButtonDeselect.setText(_translate("MainWindow", "Deselect all", None))
        self.pushButtonDeselect.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Tools", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionDarsteller.setText(_translate("MainWindow", "Actor", None))
        self.actionDarsteller.setToolTip(_translate("MainWindow", "Search for actor, Ctrl+D", None))
        self.actionDarsteller.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionCd.setText(_translate("MainWindow", "cd", None))
        self.actionCd.setToolTip(_translate("MainWindow", "Search for storage medium, Ctrl+M", None))
        self.actionCd.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionTitel.setText(_translate("MainWindow", "title", None))
        self.actionTitel.setToolTip(_translate("MainWindow", "Search for title, Ctrl+T", None))
        self.actionTitel.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionOriginal.setText(_translate("MainWindow", "original", None))
        self.actionOriginal.setToolTip(_translate("MainWindow", "Search for original, Ctrl+O", None))
        self.actionOriginal.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionVid.setText(_translate("MainWindow", "vid", None))
        self.actionVid.setToolTip(_translate("MainWindow", "Filter on movies available", None))
        self.actionCheckBoxDVDCover.setText(_translate("MainWindow", "checkBoxDVDCover", None))
        self.actionCheckBoxDVDCover.setToolTip(_translate("MainWindow", "Show only DVD covers", None))
        self.actionSuche.setText(_translate("MainWindow", "search", None))
        self.actionSuche.setToolTip(_translate("MainWindow", "Extended search, Ctrl+F", None))
        self.actionSuche.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.actionDrucken.setText(_translate("MainWindow", "print", None))
        self.actionDrucken.setToolTip(_translate("MainWindow", "Print, Ctrl+P", None))
        self.actionDrucken.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionSuchfeld.setText(_translate("MainWindow", "search field", None))
        self.actionSuchbegriffe.setText(_translate("MainWindow", "search terms", None))
        self.actionSuchbegriffe.setToolTip(_translate("MainWindow", "Edit search terms, Ctrl+S", None))
        self.actionSuchbegriffe.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionLand.setText(_translate("MainWindow", "country", None))
        self.actionLand.setToolTip(_translate("MainWindow", "Edit table of countries, Alt+L", None))
        self.actionLand.setShortcut(_translate("MainWindow", "Alt+L", None))
        self.actionFirst.setText(_translate("MainWindow", "first", None))
        self.actionFirst.setToolTip(_translate("MainWindow", "go to first page, F6", None))
        self.actionFirst.setShortcut(_translate("MainWindow", "F6", None))
        self.actionPrev.setText(_translate("MainWindow", "Prev", None))
        self.actionPrev.setToolTip(_translate("MainWindow", "1 page back, F7", None))
        self.actionPrev.setShortcut(_translate("MainWindow", "F7", None))
        self.actionNext.setText(_translate("MainWindow", "Next", None))
        self.actionNext.setToolTip(_translate("MainWindow", "Next page, F8", None))
        self.actionNext.setShortcut(_translate("MainWindow", "F8", None))
        self.actionLast.setText(_translate("MainWindow", "Last", None))
        self.actionLast.setToolTip(_translate("MainWindow", "Go to last page, F9", None))
        self.actionLast.setShortcut(_translate("MainWindow", "F9", None))
        self.actionAnzahlBilder.setText(_translate("MainWindow", "quantityofImages", None))
        self.actionUndo.setText(_translate("MainWindow", "undo", None))
        self.actionUndo.setToolTip(_translate("MainWindow", "recover, Ctrl+W", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionDarstellerUebernehmen.setText(_translate("MainWindow", "Adopt actor", None))
        self.actionDarstellerUebernehmen.setToolTip(_translate("MainWindow", "Adopt actor", None))
        self.actionAnzeigenOriginal.setText(_translate("MainWindow", "Show all scenes of the movie", None))
        self.actionAnzeigenOriginal.setToolTip(_translate("MainWindow", "Show all scenes of the movie", None))
        self.actionSortieren_nach_Darsteller.setText(_translate("MainWindow", "Sort on actors", None))
        self.actionSortieren_nach_Darsteller.setToolTip(_translate("MainWindow", "Sort on actors", None))
        self.actionSortieren_nach_CD.setText(_translate("MainWindow", "Sort on CD", None))
        self.actionSortieren_nach_CD.setToolTip(_translate("MainWindow", "Sort on CD", None))
        self.actionSortieren_nach_Titel.setText(_translate("MainWindow", "Sort on title", None))
        self.actionSortieren_nach_Titel.setToolTip(_translate("MainWindow", "Sort on title", None))
        self.actionOriginal_umbenennen.setText(_translate("MainWindow", "Rename original title", None))
        self.actionOriginal_umbenennen.setToolTip(_translate("MainWindow", "Rename original title", None))
        self.actionOriginal_weitere.setText(_translate("MainWindow", "Add more titles", None))
        self.actionOriginal_weitere.setToolTip(_translate("MainWindow", "Add more titles", None))
        self.actionSortieren_nach_Original.setText(_translate("MainWindow", "Sort on original title", None))
        self.actionSortieren_nach_Original.setToolTip(_translate("MainWindow", "Sort on original title", None))
        self.actionCovergross.setText(_translate("MainWindow", "Show cover fullscale", None))
        self.actionCovergross.setToolTip(_translate("MainWindow", "Show cover fullscale", None))
        self.actionBildLoeschen.setText(_translate("MainWindow", "Delete image file(s)", None))
        self.actionBildLoeschen.setToolTip(_translate("MainWindow", "Delete image file(s)", None))
        self.actionAnzeigenPaar.setText(_translate("MainWindow", "Show pairing", None))
        self.actionAnzeigenPaar.setToolTip(_translate("MainWindow", "Show pairing", None))
        self.actionBildanzeigegross.setText(_translate("MainWindow", "Show image fullscale", None))
        self.actionBildanzeigegross.setToolTip(_translate("MainWindow", "Show image fullscale", None))
        self.actionFilm_zeigen.setText(_translate("MainWindow", "Show movie", None))
        self.actionFilm_zeigen.setToolTip(_translate("MainWindow", "Show movie", None))
        self.actionCSZeigen.setText(_translate("MainWindow", "show", None))
        self.actionCSZeigen.setToolTip(_translate("MainWindow", "show", None))
        self.actionNeueingabe.setText(_translate("MainWindow", "new", None))
        self.actionNeueingabe.setToolTip(_translate("MainWindow", "Add new movie, F5", None))
        self.actionNeueingabe.setShortcut(_translate("MainWindow", "F5", None))
        self.actionOnHelp.setText(_translate("MainWindow", "Help", None))
        self.actionOnHelp.setToolTip(_translate("MainWindow", "Help, F1", None))
        self.actionOnHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionOriginalIntoClipboard.setText(_translate("MainWindow", "Put original title into clipboard", None))
        self.actionOriginalIntoClipboard.setToolTip(_translate("MainWindow", "<html><head/><body><p>Put original title into clipboard of the PorDB</p></body></html>", None))
        self.actionRedoImageChange.setText(_translate("MainWindow", "Redo image change", None))
        self.actionRedoImageChange.setToolTip(_translate("MainWindow", "Redo image change", None))
        self.actionGetUrl.setText(_translate("MainWindow", "Put actors URL into clipboard", None))
        self.actionGetUrl.setToolTip(_translate("MainWindow", "<html><head/><body><p>Get URL form database and put it into clipboard</p></body></html>", None))
        self.actionGoToUrl.setText(_translate("MainWindow", "Go to website of this actor", None))
        self.actionGoToUrl.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go to website of this actor</p></body></html>", None))
        self.actionAnzeigenTitle.setText(_translate("MainWindow", "Show all scenes with similar title", None))
        self.actionAnzeigenTitle.setToolTip(_translate("MainWindow", "Show all scenes with similar title", None))
        self.actionShowDetails.setText(_translate("MainWindow", "Show actors details", None))
        self.actionShowDetails.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show actors details</p></body></html>", None))

from PyQt4 import QtWebKit
