# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_darstellerneu.ui'
#
# Created: Thu Aug  6 19:00:05 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(747, 262)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 36, 711, 151))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxDarstellerneuGeschlecht = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuGeschlecht.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuGeschlecht.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuGeschlecht.setObjectName(_fromUtf8("comboBoxDarstellerneuGeschlecht"))
        self.comboBoxDarstellerneuGeschlecht.addItem(_fromUtf8(""))
        self.comboBoxDarstellerneuGeschlecht.setItemText(0, _fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/male.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuGeschlecht.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/female.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuGeschlecht.addItem(icon2, _fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxDarstellerneuGeschlecht, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxDarstellerneuHaarfarbe = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuHaarfarbe.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuHaarfarbe.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuHaarfarbe.setObjectName(_fromUtf8("comboBoxDarstellerneuHaarfarbe"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/blond.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuHaarfarbe.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/brown.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuHaarfarbe.addItem(icon4, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuHaarfarbe.addItem(icon5, _fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/black.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuHaarfarbe.addItem(icon6, _fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxDarstellerneuHaarfarbe, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxDarstellerneuNation = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxDarstellerneuNation.setObjectName(_fromUtf8("comboBoxDarstellerneuNation"))
        self.gridLayout.addWidget(self.comboBoxDarstellerneuNation, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditDarstellerneuTattoo = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditDarstellerneuTattoo.setObjectName(_fromUtf8("lineEditDarstellerneuTattoo"))
        self.gridLayout.addWidget(self.lineEditDarstellerneuTattoo, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBoxDarstellerneuEthnic = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuEthnic.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuEthnic.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuEthnic.setObjectName(_fromUtf8("comboBoxDarstellerneuEthnic"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/white.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuEthnic.addItem(icon7, _fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/yellow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxDarstellerneuEthnic.addItem(icon8, _fromUtf8(""))
        self.comboBoxDarstellerneuEthnic.addItem(icon6, _fromUtf8(""))
        self.comboBoxDarstellerneuEthnic.addItem(icon4, _fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxDarstellerneuEthnic, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.pushButtonDarstellerneuSpeichern = QtGui.QPushButton(Dialog)
        self.pushButtonDarstellerneuSpeichern.setObjectName(_fromUtf8("pushButtonDarstellerneuSpeichern"))
        self.gridLayout_2.addWidget(self.pushButtonDarstellerneuSpeichern, 1, 0, 1, 1)
        self.pushButtonDarstellerneuCancel = QtGui.QPushButton(Dialog)
        self.pushButtonDarstellerneuCancel.setObjectName(_fromUtf8("pushButtonDarstellerneuCancel"))
        self.gridLayout_2.addWidget(self.pushButtonDarstellerneuCancel, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "New actor", None))
        self.groupBox.setTitle(_translate("Dialog", "Enter new actor", None))
        self.label.setText(_translate("Dialog", "Gender", None))
        self.comboBoxDarstellerneuGeschlecht.setItemText(1, _translate("Dialog", "m", None))
        self.comboBoxDarstellerneuGeschlecht.setItemText(2, _translate("Dialog", "w", None))
        self.label_2.setText(_translate("Dialog", "Hair color", None))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(0, _translate("Dialog", "bl", None))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(1, _translate("Dialog", "br", None))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(2, _translate("Dialog", "r", None))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(3, _translate("Dialog", "s", None))
        self.label_3.setText(_translate("Dialog", "Nation", None))
        self.label_4.setText(_translate("Dialog", "Tattoo", None))
        self.label_5.setText(_translate("Dialog", "Ethnic", None))
        self.comboBoxDarstellerneuEthnic.setItemText(0, _translate("Dialog", "w", None))
        self.comboBoxDarstellerneuEthnic.setItemText(1, _translate("Dialog", "a", None))
        self.comboBoxDarstellerneuEthnic.setItemText(2, _translate("Dialog", "s", None))
        self.comboBoxDarstellerneuEthnic.setItemText(3, _translate("Dialog", "l", None))
        self.pushButtonDarstellerneuSpeichern.setText(_translate("Dialog", "Save", None))
        self.pushButtonDarstellerneuCancel.setText(_translate("Dialog", "Back", None))

