# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_darstellerneu.ui'
#
# Created: Tue Mar 13 22:32:20 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(747, 262)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 36, 711, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxDarstellerneuGeschlecht = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuGeschlecht.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuGeschlecht.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuGeschlecht.setObjectName("comboBoxDarstellerneuGeschlecht")
        self.comboBoxDarstellerneuGeschlecht.addItem("")
        self.comboBoxDarstellerneuGeschlecht.setItemText(0, "")
        self.comboBoxDarstellerneuGeschlecht.addItem("")
        self.comboBoxDarstellerneuGeschlecht.addItem("")
        self.gridLayout.addWidget(self.comboBoxDarstellerneuGeschlecht, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxDarstellerneuHaarfarbe = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuHaarfarbe.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuHaarfarbe.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuHaarfarbe.setObjectName("comboBoxDarstellerneuHaarfarbe")
        self.comboBoxDarstellerneuHaarfarbe.addItem("")
        self.comboBoxDarstellerneuHaarfarbe.addItem("")
        self.comboBoxDarstellerneuHaarfarbe.addItem("")
        self.comboBoxDarstellerneuHaarfarbe.addItem("")
        self.gridLayout.addWidget(self.comboBoxDarstellerneuHaarfarbe, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxDarstellerneuNation = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxDarstellerneuNation.setObjectName("comboBoxDarstellerneuNation")
        self.gridLayout.addWidget(self.comboBoxDarstellerneuNation, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditDarstellerneuTattoo = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditDarstellerneuTattoo.setObjectName("lineEditDarstellerneuTattoo")
        self.gridLayout.addWidget(self.lineEditDarstellerneuTattoo, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBoxDarstellerneuEthnic = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDarstellerneuEthnic.sizePolicy().hasHeightForWidth())
        self.comboBoxDarstellerneuEthnic.setSizePolicy(sizePolicy)
        self.comboBoxDarstellerneuEthnic.setObjectName("comboBoxDarstellerneuEthnic")
        self.comboBoxDarstellerneuEthnic.addItem("")
        self.comboBoxDarstellerneuEthnic.addItem("")
        self.comboBoxDarstellerneuEthnic.addItem("")
        self.comboBoxDarstellerneuEthnic.addItem("")
        self.gridLayout.addWidget(self.comboBoxDarstellerneuEthnic, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.pushButtonDarstellerneuSpeichern = QtGui.QPushButton(Dialog)
        self.pushButtonDarstellerneuSpeichern.setObjectName("pushButtonDarstellerneuSpeichern")
        self.gridLayout_2.addWidget(self.pushButtonDarstellerneuSpeichern, 1, 0, 1, 1)
        self.pushButtonDarstellerneuCancel = QtGui.QPushButton(Dialog)
        self.pushButtonDarstellerneuCancel.setObjectName("pushButtonDarstellerneuCancel")
        self.gridLayout_2.addWidget(self.pushButtonDarstellerneuCancel, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "New actor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Enter new actor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuGeschlecht.setItemText(1, QtGui.QApplication.translate("Dialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuGeschlecht.setItemText(2, QtGui.QApplication.translate("Dialog", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Hair color", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(0, QtGui.QApplication.translate("Dialog", "bl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(1, QtGui.QApplication.translate("Dialog", "br", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(2, QtGui.QApplication.translate("Dialog", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuHaarfarbe.setItemText(3, QtGui.QApplication.translate("Dialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Tattoo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Ethnic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuEthnic.setItemText(0, QtGui.QApplication.translate("Dialog", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuEthnic.setItemText(1, QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuEthnic.setItemText(2, QtGui.QApplication.translate("Dialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerneuEthnic.setItemText(3, QtGui.QApplication.translate("Dialog", "l", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDarstellerneuSpeichern.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDarstellerneuCancel.setText(QtGui.QApplication.translate("Dialog", "Back", None, QtGui.QApplication.UnicodeUTF8))

