# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_suchen.ui'
#
# Created: Thu Oct 20 21:05:04 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ErweiterteSuche(object):
    def setupUi(self, ErweiterteSuche):
        ErweiterteSuche.setObjectName(_fromUtf8("ErweiterteSuche"))
        ErweiterteSuche.resize(832, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ErweiterteSuche.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(ErweiterteSuche)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(ErweiterteSuche)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditDarsteller = QtGui.QLineEdit(self.groupBox)
        self.lineEditDarsteller.setObjectName(_fromUtf8("lineEditDarsteller"))
        self.gridLayout.addWidget(self.lineEditDarsteller, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditCD = QtGui.QLineEdit(self.groupBox)
        self.lineEditCD.setObjectName(_fromUtf8("lineEditCD"))
        self.gridLayout.addWidget(self.lineEditCD, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditTitel = QtGui.QLineEdit(self.groupBox)
        self.lineEditTitel.setObjectName(_fromUtf8("lineEditTitel"))
        self.gridLayout.addWidget(self.lineEditTitel, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditOriginal = QtGui.QLineEdit(self.groupBox)
        self.lineEditOriginal.setObjectName(_fromUtf8("lineEditOriginal"))
        self.gridLayout.addWidget(self.lineEditOriginal, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBoxVid = QtGui.QCheckBox(self.groupBox)
        self.checkBoxVid.setToolTip(_fromUtf8(""))
        self.checkBoxVid.setText(_fromUtf8(""))
        self.checkBoxVid.setObjectName(_fromUtf8("checkBoxVid"))
        self.gridLayout.addWidget(self.checkBoxVid, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.checkBoxWatched = QtGui.QCheckBox(self.groupBox)
        self.checkBoxWatched.setText(_fromUtf8(""))
        self.checkBoxWatched.setObjectName(_fromUtf8("checkBoxWatched"))
        self.gridLayout.addWidget(self.checkBoxWatched, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.comboBoxCS = QtGui.QComboBox(self.groupBox)
        self.comboBoxCS.setMaximumSize(QtCore.QSize(723, 16777215))
        self.comboBoxCS.setObjectName(_fromUtf8("comboBoxCS"))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.setItemText(0, _fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCS, 6, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonStar1 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar1.sizePolicy().hasHeightForWidth())
        self.pushButtonStar1.setSizePolicy(sizePolicy)
        self.pushButtonStar1.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar1.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/non-starred.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStar1.setIcon(icon1)
        self.pushButtonStar1.setFlat(True)
        self.pushButtonStar1.setObjectName(_fromUtf8("pushButtonStar1"))
        self.horizontalLayout_2.addWidget(self.pushButtonStar1)
        self.pushButtonStar2 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar2.sizePolicy().hasHeightForWidth())
        self.pushButtonStar2.setSizePolicy(sizePolicy)
        self.pushButtonStar2.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar2.setText(_fromUtf8(""))
        self.pushButtonStar2.setIcon(icon1)
        self.pushButtonStar2.setFlat(True)
        self.pushButtonStar2.setObjectName(_fromUtf8("pushButtonStar2"))
        self.horizontalLayout_2.addWidget(self.pushButtonStar2)
        self.pushButtonStar3 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar3.sizePolicy().hasHeightForWidth())
        self.pushButtonStar3.setSizePolicy(sizePolicy)
        self.pushButtonStar3.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar3.setText(_fromUtf8(""))
        self.pushButtonStar3.setIcon(icon1)
        self.pushButtonStar3.setFlat(True)
        self.pushButtonStar3.setObjectName(_fromUtf8("pushButtonStar3"))
        self.horizontalLayout_2.addWidget(self.pushButtonStar3)
        self.pushButtonStar4 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar4.sizePolicy().hasHeightForWidth())
        self.pushButtonStar4.setSizePolicy(sizePolicy)
        self.pushButtonStar4.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar4.setText(_fromUtf8(""))
        self.pushButtonStar4.setIcon(icon1)
        self.pushButtonStar4.setFlat(True)
        self.pushButtonStar4.setObjectName(_fromUtf8("pushButtonStar4"))
        self.horizontalLayout_2.addWidget(self.pushButtonStar4)
        self.pushButtonStar5 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar5.sizePolicy().hasHeightForWidth())
        self.pushButtonStar5.setSizePolicy(sizePolicy)
        self.pushButtonStar5.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar5.setText(_fromUtf8(""))
        self.pushButtonStar5.setIcon(icon1)
        self.pushButtonStar5.setFlat(True)
        self.pushButtonStar5.setObjectName(_fromUtf8("pushButtonStar5"))
        self.horizontalLayout_2.addWidget(self.pushButtonStar5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEditRemarks = QtGui.QLineEdit(self.groupBox)
        self.lineEditRemarks.setObjectName(_fromUtf8("lineEditRemarks"))
        self.gridLayout.addWidget(self.lineEditRemarks, 8, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonSuchen = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonSuchen.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/suchen.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSuchen.setIcon(icon2)
        self.pushButtonSuchen.setObjectName(_fromUtf8("pushButtonSuchen"))
        self.horizontalLayout.addWidget(self.pushButtonSuchen)
        self.pushButtonRefresh = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonRefresh.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/clear_l.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon3)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonCancel = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonCancel.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/dialog-cancel.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon4)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ErweiterteSuche)
        QtCore.QMetaObject.connectSlotsByName(ErweiterteSuche)
        ErweiterteSuche.setTabOrder(self.lineEditDarsteller, self.lineEditCD)
        ErweiterteSuche.setTabOrder(self.lineEditCD, self.lineEditTitel)
        ErweiterteSuche.setTabOrder(self.lineEditTitel, self.lineEditOriginal)
        ErweiterteSuche.setTabOrder(self.lineEditOriginal, self.checkBoxVid)
        ErweiterteSuche.setTabOrder(self.checkBoxVid, self.checkBoxWatched)
        ErweiterteSuche.setTabOrder(self.checkBoxWatched, self.comboBoxCS)
        ErweiterteSuche.setTabOrder(self.comboBoxCS, self.pushButtonSuchen)
        ErweiterteSuche.setTabOrder(self.pushButtonSuchen, self.pushButtonRefresh)
        ErweiterteSuche.setTabOrder(self.pushButtonRefresh, self.pushButtonCancel)

    def retranslateUi(self, ErweiterteSuche):
        ErweiterteSuche.setWindowTitle(_translate("ErweiterteSuche", "Extended search", None))
        self.groupBox.setTitle(_translate("ErweiterteSuche", "Search criteria", None))
        self.label.setText(_translate("ErweiterteSuche", "Actor", None))
        self.lineEditDarsteller.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for actors</p></body></html>", None))
        self.label_2.setText(_translate("ErweiterteSuche", "CD", None))
        self.lineEditCD.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None))
        self.lineEditCD.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for data storage medium</p></body></html>", None))
        self.label_3.setText(_translate("ErweiterteSuche", "Title", None))
        self.lineEditTitel.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for title</p></body></html>", None))
        self.label_4.setText(_translate("ErweiterteSuche", "Original", None))
        self.lineEditOriginal.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None))
        self.lineEditOriginal.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for original title</p></body></html>", None))
        self.label_5.setText(_translate("ErweiterteSuche", "Video present", None))
        self.checkBoxVid.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Filter search results only for videos which are present</p></body></html>", None))
        self.label_7.setText(_translate("ErweiterteSuche", "Video watched", None))
        self.label_6.setText(_translate("ErweiterteSuche", "CS", None))
        self.comboBoxCS.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Filter search results with cumshots</p></body></html>", None))
        self.comboBoxCS.setItemText(1, _translate("ErweiterteSuche", "f Facial", None))
        self.comboBoxCS.setItemText(2, _translate("ErweiterteSuche", "h Handjob", None))
        self.comboBoxCS.setItemText(3, _translate("ErweiterteSuche", "t Tits", None))
        self.comboBoxCS.setItemText(4, _translate("ErweiterteSuche", "c Creampie", None))
        self.comboBoxCS.setItemText(5, _translate("ErweiterteSuche", "x Analcreampie", None))
        self.comboBoxCS.setItemText(6, _translate("ErweiterteSuche", "o Oralcreampie", None))
        self.comboBoxCS.setItemText(7, _translate("ErweiterteSuche", "v Cunt", None))
        self.comboBoxCS.setItemText(8, _translate("ErweiterteSuche", "b Belly", None))
        self.comboBoxCS.setItemText(9, _translate("ErweiterteSuche", "a Ass", None))
        self.comboBoxCS.setItemText(10, _translate("ErweiterteSuche", "s Others", None))
        self.comboBoxCS.setItemText(11, _translate("ErweiterteSuche", "k No", None))
        self.label_8.setText(_translate("ErweiterteSuche", "Rating", None))
        self.label_9.setText(_translate("ErweiterteSuche", "Remarks", None))
        self.pushButtonSuchen.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p>Search (enter)</p></body></html>", None))
        self.pushButtonSuchen.setWhatsThis(_translate("ErweiterteSuche", "Start search", None))
        self.pushButtonSuchen.setShortcut(_translate("ErweiterteSuche", "Enter", None))
        self.pushButtonRefresh.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p>Clear all search fields, alt+L</p></body></html>", None))
        self.pushButtonRefresh.setWhatsThis(_translate("ErweiterteSuche", "Clear all fields in search form", None))
        self.pushButtonRefresh.setShortcut(_translate("ErweiterteSuche", "Alt+L", None))
        self.pushButtonCancel.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p>Cancel (escape)</p></body></html>", None))
        self.pushButtonCancel.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Cancel search</p></body></html>", None))

