# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_mass_change.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 142)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonVorhandenJa = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonVorhandenJa.setObjectName("radioButtonVorhandenJa")
        self.horizontalLayout_2.addWidget(self.radioButtonVorhandenJa)
        self.radioButtonVorhandenNein = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonVorhandenNein.setObjectName("radioButtonVorhandenNein")
        self.horizontalLayout_2.addWidget(self.radioButtonVorhandenNein)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label.raise_()
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonWatchedJa = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonWatchedJa.setObjectName("radioButtonWatchedJa")
        self.horizontalLayout_3.addWidget(self.radioButtonWatchedJa)
        self.radioButtonWatchedNein = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonWatchedNein.setObjectName("radioButtonWatchedNein")
        self.horizontalLayout_3.addWidget(self.radioButtonWatchedNein)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBoxResolution = QtWidgets.QComboBox(self.frame_3)
        self.comboBoxResolution.setObjectName("comboBoxResolution")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.setItemText(0, "")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.verticalLayout.addWidget(self.comboBoxResolution)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mass change"))
        self.label.setText(_translate("Dialog", "Present"))
        self.radioButtonVorhandenJa.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Mark here when video is NOT present.</p></body></html>"))
        self.radioButtonVorhandenJa.setText(_translate("Dialog", "Yes"))
        self.radioButtonVorhandenNein.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Mark here when video is present.</p></body></html>"))
        self.radioButtonVorhandenNein.setText(_translate("Dialog", "No"))
        self.label_3.setText(_translate("Dialog", "Watched"))
        self.radioButtonWatchedJa.setText(_translate("Dialog", "Yes"))
        self.radioButtonWatchedNein.setText(_translate("Dialog", "No"))
        self.label_2.setText(_translate("Dialog", "Resolution"))
        self.comboBoxResolution.setItemText(1, _translate("Dialog", "SD"))
        self.comboBoxResolution.setItemText(2, _translate("Dialog", "HD 720p"))
        self.comboBoxResolution.setItemText(3, _translate("Dialog", "HD 1080p"))
        self.comboBoxResolution.setItemText(4, _translate("Dialog", "UltraHD"))
        self.comboBoxResolution.setItemText(5, _translate("Dialog", "Unknown"))

