# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_suchen.ui'
#
# Created: Mon Nov 18 23:36:38 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ErweiterteSuche(object):
    def setupUi(self, ErweiterteSuche):
        ErweiterteSuche.setObjectName(_fromUtf8("ErweiterteSuche"))
        ErweiterteSuche.resize(832, 291)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ErweiterteSuche.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(ErweiterteSuche)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(ErweiterteSuche)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditDarsteller = QtGui.QLineEdit(self.groupBox)
        self.lineEditDarsteller.setObjectName(_fromUtf8("lineEditDarsteller"))
        self.gridLayout.addWidget(self.lineEditDarsteller, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditCD = QtGui.QLineEdit(self.groupBox)
        self.lineEditCD.setObjectName(_fromUtf8("lineEditCD"))
        self.gridLayout.addWidget(self.lineEditCD, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditTitel = QtGui.QLineEdit(self.groupBox)
        self.lineEditTitel.setObjectName(_fromUtf8("lineEditTitel"))
        self.gridLayout.addWidget(self.lineEditTitel, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditOriginal = QtGui.QLineEdit(self.groupBox)
        self.lineEditOriginal.setObjectName(_fromUtf8("lineEditOriginal"))
        self.gridLayout.addWidget(self.lineEditOriginal, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBoxVid = QtGui.QCheckBox(self.groupBox)
        self.checkBoxVid.setToolTip(_fromUtf8(""))
        self.checkBoxVid.setText(_fromUtf8(""))
        self.checkBoxVid.setObjectName(_fromUtf8("checkBoxVid"))
        self.gridLayout.addWidget(self.checkBoxVid, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBoxCS = QtGui.QComboBox(self.groupBox)
        self.comboBoxCS.setMaximumSize(QtCore.QSize(723, 16777215))
        self.comboBoxCS.setObjectName(_fromUtf8("comboBoxCS"))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.setItemText(0, _fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCS, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.pushButtonSuchen = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonSuchen.setToolTip(_fromUtf8(""))
        self.pushButtonSuchen.setObjectName(_fromUtf8("pushButtonSuchen"))
        self.hboxlayout.addWidget(self.pushButtonSuchen)
        self.pushButtonRefresh = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonRefresh.setToolTip(_fromUtf8(""))
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.hboxlayout.addWidget(self.pushButtonRefresh)
        self.pushButtonCancel = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.hboxlayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.hboxlayout)

        self.retranslateUi(ErweiterteSuche)
        QtCore.QMetaObject.connectSlotsByName(ErweiterteSuche)
        ErweiterteSuche.setTabOrder(self.lineEditDarsteller, self.lineEditCD)
        ErweiterteSuche.setTabOrder(self.lineEditCD, self.lineEditTitel)
        ErweiterteSuche.setTabOrder(self.lineEditTitel, self.lineEditOriginal)
        ErweiterteSuche.setTabOrder(self.lineEditOriginal, self.checkBoxVid)
        ErweiterteSuche.setTabOrder(self.checkBoxVid, self.comboBoxCS)
        ErweiterteSuche.setTabOrder(self.comboBoxCS, self.pushButtonSuchen)
        ErweiterteSuche.setTabOrder(self.pushButtonSuchen, self.pushButtonRefresh)
        ErweiterteSuche.setTabOrder(self.pushButtonRefresh, self.pushButtonCancel)

    def retranslateUi(self, ErweiterteSuche):
        ErweiterteSuche.setWindowTitle(_translate("ErweiterteSuche", "Extended search", None))
        self.groupBox.setTitle(_translate("ErweiterteSuche", "Search criteria", None))
        self.label.setText(_translate("ErweiterteSuche", "Actor", None))
        self.lineEditDarsteller.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for actors</p></body></html>", None))
        self.label_2.setText(_translate("ErweiterteSuche", "CD", None))
        self.lineEditCD.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None))
        self.lineEditCD.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for data storage medium</p></body></html>", None))
        self.label_3.setText(_translate("ErweiterteSuche", "Title", None))
        self.lineEditTitel.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for title</p></body></html>", None))
        self.label_4.setText(_translate("ErweiterteSuche", "Original", None))
        self.lineEditOriginal.setToolTip(_translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None))
        self.lineEditOriginal.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Search for original title</p></body></html>", None))
        self.label_5.setText(_translate("ErweiterteSuche", "Video present", None))
        self.checkBoxVid.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Filter search results only for videos which are present</p></body></html>", None))
        self.label_6.setText(_translate("ErweiterteSuche", "CS", None))
        self.comboBoxCS.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Filter search results with cumshots</p></body></html>", None))
        self.comboBoxCS.setItemText(1, _translate("ErweiterteSuche", "f Facial", None))
        self.comboBoxCS.setItemText(2, _translate("ErweiterteSuche", "h Handjob", None))
        self.comboBoxCS.setItemText(3, _translate("ErweiterteSuche", "t Tits", None))
        self.comboBoxCS.setItemText(4, _translate("ErweiterteSuche", "c Creampie", None))
        self.comboBoxCS.setItemText(5, _translate("ErweiterteSuche", "x Analcreampie", None))
        self.comboBoxCS.setItemText(6, _translate("ErweiterteSuche", "o Oralcreampie", None))
        self.comboBoxCS.setItemText(7, _translate("ErweiterteSuche", "v Cunt", None))
        self.comboBoxCS.setItemText(8, _translate("ErweiterteSuche", "b Belly", None))
        self.comboBoxCS.setItemText(9, _translate("ErweiterteSuche", "a Ass", None))
        self.comboBoxCS.setItemText(10, _translate("ErweiterteSuche", "s Others", None))
        self.comboBoxCS.setItemText(11, _translate("ErweiterteSuche", "k No", None))
        self.pushButtonSuchen.setWhatsThis(_translate("ErweiterteSuche", "Start search", None))
        self.pushButtonSuchen.setText(_translate("ErweiterteSuche", "Search", None))
        self.pushButtonSuchen.setShortcut(_translate("ErweiterteSuche", "Enter", None))
        self.pushButtonRefresh.setWhatsThis(_translate("ErweiterteSuche", "Clear all fields in search form", None))
        self.pushButtonRefresh.setText(_translate("ErweiterteSuche", "Refresh", None))
        self.pushButtonCancel.setWhatsThis(_translate("ErweiterteSuche", "<html><head/><body><p>Cancel search</p></body></html>", None))
        self.pushButtonCancel.setText(_translate("ErweiterteSuche", "Cancel", None))

