# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_iafd.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DatenausderIAFD(object):
    def setupUi(self, DatenausderIAFD):
        DatenausderIAFD.setObjectName("DatenausderIAFD")
        DatenausderIAFD.resize(937, 632)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatenausderIAFD.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(DatenausderIAFD)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxBild = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxBild.setText("")
        self.checkBoxBild.setObjectName("checkBoxBild")
        self.horizontalLayout.addWidget(self.checkBoxBild)
        self.labelBild = QtWidgets.QLabel(DatenausderIAFD)
        self.labelBild.setMinimumSize(QtCore.QSize(231, 251))
        self.labelBild.setObjectName("labelBild")
        self.horizontalLayout.addWidget(self.labelBild)
        self.labelName = QtWidgets.QLabel(DatenausderIAFD)
        self.labelName.setEnabled(True)
        self.labelName.setMinimumSize(QtCore.QSize(401, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout.addWidget(self.labelName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxGeboren = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxGeboren.setText("")
        self.checkBoxGeboren.setObjectName("checkBoxGeboren")
        self.gridLayout.addWidget(self.checkBoxGeboren, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.checkBoxEthnic = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxEthnic.setText("")
        self.checkBoxEthnic.setObjectName("checkBoxEthnic")
        self.gridLayout.addWidget(self.checkBoxEthnic, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.checkBoxPseudo = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxPseudo.setText("")
        self.checkBoxPseudo.setObjectName("checkBoxPseudo")
        self.gridLayout.addWidget(self.checkBoxPseudo, 2, 0, 1, 1)
        self.checkBoxTattos = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxTattos.setText("")
        self.checkBoxTattos.setObjectName("checkBoxTattos")
        self.gridLayout.addWidget(self.checkBoxTattos, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.checkBoxName = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxName.setText("")
        self.checkBoxName.setObjectName("checkBoxName")
        self.gridLayout.addWidget(self.checkBoxName, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(DatenausderIAFD)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.lineEditTattos = QtWidgets.QLineEdit(DatenausderIAFD)
        self.lineEditTattos.setObjectName("lineEditTattos")
        self.gridLayout.addWidget(self.lineEditTattos, 10, 2, 1, 1)
        self.checkBoxHaare = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxHaare.setText("")
        self.checkBoxHaare.setObjectName("checkBoxHaare")
        self.gridLayout.addWidget(self.checkBoxHaare, 8, 0, 1, 1)
        self.checkBoxLand = QtWidgets.QCheckBox(DatenausderIAFD)
        self.checkBoxLand.setText("")
        self.checkBoxLand.setObjectName("checkBoxLand")
        self.gridLayout.addWidget(self.checkBoxLand, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 1, 1, 1)
        self.lineEditPseudo = QtWidgets.QLineEdit(DatenausderIAFD)
        self.lineEditPseudo.setObjectName("lineEditPseudo")
        self.gridLayout.addWidget(self.lineEditPseudo, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.lineEditGeschlecht = QtWidgets.QLineEdit(DatenausderIAFD)
        self.lineEditGeschlecht.setReadOnly(True)
        self.lineEditGeschlecht.setObjectName("lineEditGeschlecht")
        self.gridLayout.addWidget(self.lineEditGeschlecht, 1, 2, 1, 1)
        self.labelBirthplace = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBirthplace.sizePolicy().hasHeightForWidth())
        self.labelBirthplace.setSizePolicy(sizePolicy)
        self.labelBirthplace.setText("")
        self.labelBirthplace.setObjectName("labelBirthplace")
        self.gridLayout.addWidget(self.labelBirthplace, 5, 2, 1, 1)
        self.labelGeboren = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGeboren.sizePolicy().hasHeightForWidth())
        self.labelGeboren.setSizePolicy(sizePolicy)
        self.labelGeboren.setText("")
        self.labelGeboren.setObjectName("labelGeboren")
        self.gridLayout.addWidget(self.labelGeboren, 3, 2, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(DatenausderIAFD)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(DatenausderIAFD)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.comboBoxNation = QtWidgets.QComboBox(DatenausderIAFD)
        self.comboBoxNation.setObjectName("comboBoxNation")
        self.gridLayout.addWidget(self.comboBoxNation, 4, 2, 1, 1)
        self.comboBoxEthnic = QtWidgets.QComboBox(DatenausderIAFD)
        self.comboBoxEthnic.setObjectName("comboBoxEthnic")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pypordb/white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxEthnic.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pypordb/yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxEthnic.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pypordb/black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxEthnic.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pypordb/brown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxEthnic.addItem(icon4, "")
        self.gridLayout.addWidget(self.comboBoxEthnic, 6, 2, 1, 1)
        self.comboBoxHaare = QtWidgets.QComboBox(DatenausderIAFD)
        self.comboBoxHaare.setObjectName("comboBoxHaare")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pypordb/blond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxHaare.addItem(icon5, "")
        self.comboBoxHaare.addItem(icon4, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("pypordb/grey.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxHaare.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("pypordb/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxHaare.addItem(icon7, "")
        self.comboBoxHaare.addItem(icon3, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("pypordb/bald.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxHaare.addItem(icon8, "")
        self.gridLayout.addWidget(self.comboBoxHaare, 8, 2, 1, 1)
        self.labelEthnic = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEthnic.sizePolicy().hasHeightForWidth())
        self.labelEthnic.setSizePolicy(sizePolicy)
        self.labelEthnic.setText("")
        self.labelEthnic.setObjectName("labelEthnic")
        self.gridLayout.addWidget(self.labelEthnic, 7, 2, 1, 1)
        self.labelHaare = QtWidgets.QLabel(DatenausderIAFD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHaare.sizePolicy().hasHeightForWidth())
        self.labelHaare.setSizePolicy(sizePolicy)
        self.labelHaare.setText("")
        self.labelHaare.setObjectName("labelHaare")
        self.gridLayout.addWidget(self.labelHaare, 9, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonRemoveBrackets = QtWidgets.QPushButton(DatenausderIAFD)
        self.pushButtonRemoveBrackets.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("pypordb/bracket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRemoveBrackets.setIcon(icon9)
        self.pushButtonRemoveBrackets.setObjectName("pushButtonRemoveBrackets")
        self.horizontalLayout_2.addWidget(self.pushButtonRemoveBrackets)
        self.pushButtonUebernehmen = QtWidgets.QPushButton(DatenausderIAFD)
        self.pushButtonUebernehmen.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("pypordb/dialog-ok.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUebernehmen.setIcon(icon10)
        self.pushButtonUebernehmen.setObjectName("pushButtonUebernehmen")
        self.horizontalLayout_2.addWidget(self.pushButtonUebernehmen)
        self.pushButtonCancel = QtWidgets.QPushButton(DatenausderIAFD)
        self.pushButtonCancel.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("pypordb/dialog-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon11)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(DatenausderIAFD)
        QtCore.QMetaObject.connectSlotsByName(DatenausderIAFD)
        DatenausderIAFD.setTabOrder(self.checkBoxBild, self.checkBoxName)
        DatenausderIAFD.setTabOrder(self.checkBoxName, self.lineEditName)
        DatenausderIAFD.setTabOrder(self.lineEditName, self.lineEditGeschlecht)
        DatenausderIAFD.setTabOrder(self.lineEditGeschlecht, self.checkBoxPseudo)
        DatenausderIAFD.setTabOrder(self.checkBoxPseudo, self.lineEditPseudo)
        DatenausderIAFD.setTabOrder(self.lineEditPseudo, self.checkBoxGeboren)
        DatenausderIAFD.setTabOrder(self.checkBoxGeboren, self.checkBoxLand)
        DatenausderIAFD.setTabOrder(self.checkBoxLand, self.checkBoxEthnic)
        DatenausderIAFD.setTabOrder(self.checkBoxEthnic, self.checkBoxHaare)
        DatenausderIAFD.setTabOrder(self.checkBoxHaare, self.checkBoxTattos)
        DatenausderIAFD.setTabOrder(self.checkBoxTattos, self.lineEditTattos)
        DatenausderIAFD.setTabOrder(self.lineEditTattos, self.pushButtonRemoveBrackets)
        DatenausderIAFD.setTabOrder(self.pushButtonRemoveBrackets, self.pushButtonUebernehmen)
        DatenausderIAFD.setTabOrder(self.pushButtonUebernehmen, self.pushButtonCancel)

    def retranslateUi(self, DatenausderIAFD):
        _translate = QtCore.QCoreApplication.translate
        DatenausderIAFD.setWindowTitle(_translate("DatenausderIAFD", "Data from the IAFD"))
        self.labelBild.setText(_translate("DatenausderIAFD", "TextLabel"))
        self.labelName.setText(_translate("DatenausderIAFD", "TextLabel"))
        self.label_7.setText(_translate("DatenausderIAFD", "Tattoos:"))
        self.label_4.setText(_translate("DatenausderIAFD", "Ethnic:"))
        self.label_3.setText(_translate("DatenausderIAFD", "Country:"))
        self.label_8.setText(_translate("DatenausderIAFD", "Name:"))
        self.label.setText(_translate("DatenausderIAFD", "Alias:"))
        self.label_2.setText(_translate("DatenausderIAFD", "Born:"))
        self.label_5.setText(_translate("DatenausderIAFD", "Hair color:"))
        self.label_9.setText(_translate("DatenausderIAFD", "Birthplace:"))
        self.label_6.setText(_translate("DatenausderIAFD", "Gender:"))
        self.comboBoxEthnic.setItemText(0, _translate("DatenausderIAFD", "w"))
        self.comboBoxEthnic.setItemText(1, _translate("DatenausderIAFD", "a"))
        self.comboBoxEthnic.setItemText(2, _translate("DatenausderIAFD", "s"))
        self.comboBoxEthnic.setItemText(3, _translate("DatenausderIAFD", "l"))
        self.comboBoxHaare.setItemText(0, _translate("DatenausderIAFD", "bl"))
        self.comboBoxHaare.setItemText(1, _translate("DatenausderIAFD", "br"))
        self.comboBoxHaare.setItemText(2, _translate("DatenausderIAFD", "gr"))
        self.comboBoxHaare.setItemText(3, _translate("DatenausderIAFD", "r"))
        self.comboBoxHaare.setItemText(4, _translate("DatenausderIAFD", "s"))
        self.comboBoxHaare.setItemText(5, _translate("DatenausderIAFD", "ba"))
        self.pushButtonRemoveBrackets.setToolTip(_translate("DatenausderIAFD", "<html><head/><body><p>Delete comments in brackets in field Alias, Ctrl+L</p></body></html>"))
        self.pushButtonRemoveBrackets.setShortcut(_translate("DatenausderIAFD", "Ctrl+D"))
        self.pushButtonUebernehmen.setToolTip(_translate("DatenausderIAFD", "<html><head/><body><p>Adopt marked data (enter)</p></body></html>"))
        self.pushButtonCancel.setToolTip(_translate("DatenausderIAFD", "<html><head/><body><p>Cancel (escape)</p></body></html>"))

