# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_neu.ui'
#
# Created: Sun Aug 27 22:03:38 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1388, 516)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(130, 59))
        self.groupBox_4.setWhatsThis(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButtonVorhandenJa = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonVorhandenJa.setObjectName(_fromUtf8("radioButtonVorhandenJa"))
        self.horizontalLayout_3.addWidget(self.radioButtonVorhandenJa)
        self.radioButtonVorhandenNein = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonVorhandenNein.setObjectName(_fromUtf8("radioButtonVorhandenNein"))
        self.horizontalLayout_3.addWidget(self.radioButtonVorhandenNein)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(130, 59))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonGesehenJa = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonGesehenJa.setObjectName(_fromUtf8("radioButtonGesehenJa"))
        self.horizontalLayout_4.addWidget(self.radioButtonGesehenJa)
        self.radioButtonGesehenNein = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonGesehenNein.setObjectName(_fromUtf8("radioButtonGesehenNein"))
        self.horizontalLayout_4.addWidget(self.radioButtonGesehenNein)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.horizontalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setMinimumSize(QtCore.QSize(130, 59))
        self.groupBox_6.setWhatsThis(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButtonCoverJa = QtGui.QRadioButton(self.groupBox_6)
        self.radioButtonCoverJa.setObjectName(_fromUtf8("radioButtonCoverJa"))
        self.horizontalLayout_6.addWidget(self.radioButtonCoverJa)
        self.radioButtonCoverNein = QtGui.QRadioButton(self.groupBox_6)
        self.radioButtonCoverNein.setObjectName(_fromUtf8("radioButtonCoverNein"))
        self.horizontalLayout_6.addWidget(self.radioButtonCoverNein)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.horizontalLayout_11.addWidget(self.groupBox_6)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_13.addWidget(self.label_8)
        self.labelOriginal = QtGui.QLabel(Dialog)
        self.labelOriginal.setText(_fromUtf8(""))
        self.labelOriginal.setObjectName(_fromUtf8("labelOriginal"))
        self.horizontalLayout_13.addWidget(self.labelOriginal)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBoxUninteressant = QtGui.QCheckBox(Dialog)
        self.checkBoxUninteressant.setObjectName(_fromUtf8("checkBoxUninteressant"))
        self.horizontalLayout_7.addWidget(self.checkBoxUninteressant)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBoxDefinition = QtGui.QComboBox(Dialog)
        self.comboBoxDefinition.setObjectName(_fromUtf8("comboBoxDefinition"))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.comboBoxDefinition.setItemText(0, _fromUtf8(""))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.comboBoxDefinition.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxDefinition)
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_7.addWidget(self.label_18)
        self.pushButtonStar1 = QtGui.QPushButton(Dialog)
        self.pushButtonStar1.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar1.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/non-starred.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStar1.setIcon(icon1)
        self.pushButtonStar1.setFlat(True)
        self.pushButtonStar1.setObjectName(_fromUtf8("pushButtonStar1"))
        self.horizontalLayout_7.addWidget(self.pushButtonStar1)
        self.pushButtonStar2 = QtGui.QPushButton(Dialog)
        self.pushButtonStar2.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar2.setText(_fromUtf8(""))
        self.pushButtonStar2.setIcon(icon1)
        self.pushButtonStar2.setFlat(True)
        self.pushButtonStar2.setObjectName(_fromUtf8("pushButtonStar2"))
        self.horizontalLayout_7.addWidget(self.pushButtonStar2)
        self.pushButtonStar3 = QtGui.QPushButton(Dialog)
        self.pushButtonStar3.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar3.setText(_fromUtf8(""))
        self.pushButtonStar3.setIcon(icon1)
        self.pushButtonStar3.setFlat(True)
        self.pushButtonStar3.setObjectName(_fromUtf8("pushButtonStar3"))
        self.horizontalLayout_7.addWidget(self.pushButtonStar3)
        self.pushButtonStar4 = QtGui.QPushButton(Dialog)
        self.pushButtonStar4.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar4.setText(_fromUtf8(""))
        self.pushButtonStar4.setIcon(icon1)
        self.pushButtonStar4.setFlat(True)
        self.pushButtonStar4.setObjectName(_fromUtf8("pushButtonStar4"))
        self.horizontalLayout_7.addWidget(self.pushButtonStar4)
        self.pushButtonStar5 = QtGui.QPushButton(Dialog)
        self.pushButtonStar5.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonStar5.setText(_fromUtf8(""))
        self.pushButtonStar5.setIcon(icon1)
        self.pushButtonStar5.setFlat(True)
        self.pushButtonStar5.setObjectName(_fromUtf8("pushButtonStar5"))
        self.horizontalLayout_7.addWidget(self.pushButtonStar5)
        self.pushButtonClearRating = QtGui.QPushButton(Dialog)
        self.pushButtonClearRating.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonClearRating.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/clear_l.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClearRating.setIcon(icon2)
        self.pushButtonClearRating.setObjectName(_fromUtf8("pushButtonClearRating"))
        self.horizontalLayout_7.addWidget(self.pushButtonClearRating)
        spacerItem1 = QtGui.QSpacerItem(358, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.spinBoxF = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxF.sizePolicy().hasHeightForWidth())
        self.spinBoxF.setSizePolicy(sizePolicy)
        self.spinBoxF.setObjectName(_fromUtf8("spinBoxF"))
        self.horizontalLayout_5.addWidget(self.spinBoxF)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBoxH = QtGui.QSpinBox(Dialog)
        self.spinBoxH.setObjectName(_fromUtf8("spinBoxH"))
        self.horizontalLayout_5.addWidget(self.spinBoxH)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBoxT = QtGui.QSpinBox(Dialog)
        self.spinBoxT.setObjectName(_fromUtf8("spinBoxT"))
        self.horizontalLayout_5.addWidget(self.spinBoxT)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.spinBoxC = QtGui.QSpinBox(Dialog)
        self.spinBoxC.setObjectName(_fromUtf8("spinBoxC"))
        self.horizontalLayout_5.addWidget(self.spinBoxC)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.spinBoxX = QtGui.QSpinBox(Dialog)
        self.spinBoxX.setObjectName(_fromUtf8("spinBoxX"))
        self.horizontalLayout_5.addWidget(self.spinBoxX)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.spinBoxO = QtGui.QSpinBox(Dialog)
        self.spinBoxO.setObjectName(_fromUtf8("spinBoxO"))
        self.horizontalLayout_5.addWidget(self.spinBoxO)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.spinBoxV = QtGui.QSpinBox(Dialog)
        self.spinBoxV.setObjectName(_fromUtf8("spinBoxV"))
        self.horizontalLayout_5.addWidget(self.spinBoxV)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.spinBoxB = QtGui.QSpinBox(Dialog)
        self.spinBoxB.setObjectName(_fromUtf8("spinBoxB"))
        self.horizontalLayout_5.addWidget(self.spinBoxB)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.spinBoxA = QtGui.QSpinBox(Dialog)
        self.spinBoxA.setObjectName(_fromUtf8("spinBoxA"))
        self.horizontalLayout_5.addWidget(self.spinBoxA)
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.spinBoxS = QtGui.QSpinBox(Dialog)
        self.spinBoxS.setObjectName(_fromUtf8("spinBoxS"))
        self.horizontalLayout_5.addWidget(self.spinBoxS)
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.spinBoxK = QtGui.QSpinBox(Dialog)
        self.spinBoxK.setObjectName(_fromUtf8("spinBoxK"))
        self.horizontalLayout_5.addWidget(self.spinBoxK)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButtonNeuDarstelleruebernehmen = QtGui.QPushButton(Dialog)
        self.pushButtonNeuDarstelleruebernehmen.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNeuDarstelleruebernehmen.setIcon(icon3)
        self.pushButtonNeuDarstelleruebernehmen.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonNeuDarstelleruebernehmen.setCheckable(False)
        self.pushButtonNeuDarstelleruebernehmen.setObjectName(_fromUtf8("pushButtonNeuDarstelleruebernehmen"))
        self.verticalLayout_3.addWidget(self.pushButtonNeuDarstelleruebernehmen)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.listWidgetW = QtGui.QListWidget(Dialog)
        self.listWidgetW.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidgetW.setObjectName(_fromUtf8("listWidgetW"))
        self.horizontalLayout_8.addWidget(self.listWidgetW)
        self.listWidgetM = QtGui.QListWidget(Dialog)
        self.listWidgetM.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidgetM.setObjectName(_fromUtf8("listWidgetM"))
        self.horizontalLayout_8.addWidget(self.listWidgetM)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonBildbeschneiden = QtGui.QPushButton(Dialog)
        self.pushButtonBildbeschneiden.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/transform-crop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBildbeschneiden.setIcon(icon4)
        self.pushButtonBildbeschneiden.setObjectName(_fromUtf8("pushButtonBildbeschneiden"))
        self.horizontalLayout.addWidget(self.pushButtonBildbeschneiden)
        self.pushButtonBildloeschen = QtGui.QPushButton(Dialog)
        self.pushButtonBildloeschen.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/user-trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBildloeschen.setIcon(icon5)
        self.pushButtonBildloeschen.setObjectName(_fromUtf8("pushButtonBildloeschen"))
        self.horizontalLayout.addWidget(self.pushButtonBildloeschen)
        self.pushButtonNeuOK = QtGui.QPushButton(Dialog)
        self.pushButtonNeuOK.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/media-floppy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNeuOK.setIcon(icon6)
        self.pushButtonNeuOK.setAutoDefault(False)
        self.pushButtonNeuOK.setDefault(True)
        self.pushButtonNeuOK.setObjectName(_fromUtf8("pushButtonNeuOK"))
        self.horizontalLayout.addWidget(self.pushButtonNeuOK)
        self.pushButtonNeuCancel = QtGui.QPushButton(Dialog)
        self.pushButtonNeuCancel.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/dialog-cancel.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNeuCancel.setIcon(icon7)
        self.pushButtonNeuCancel.setObjectName(_fromUtf8("pushButtonNeuCancel"))
        self.horizontalLayout.addWidget(self.pushButtonNeuCancel)
        self.pushButtonNeuDelete = QtGui.QPushButton(Dialog)
        self.pushButtonNeuDelete.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/user-trash.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNeuDelete.setIcon(icon8)
        self.pushButtonNeuDelete.setObjectName(_fromUtf8("pushButtonNeuDelete"))
        self.horizontalLayout.addWidget(self.pushButtonNeuDelete)
        self.pushButtonVerz = QtGui.QPushButton(Dialog)
        self.pushButtonVerz.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/folder.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVerz.setIcon(icon9)
        self.pushButtonVerz.setObjectName(_fromUtf8("pushButtonVerz"))
        self.horizontalLayout.addWidget(self.pushButtonVerz)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelNeuBildanzeige = QtGui.QLabel(self.groupBox_2)
        self.labelNeuBildanzeige.setText(_fromUtf8(""))
        self.labelNeuBildanzeige.setObjectName(_fromUtf8("labelNeuBildanzeige"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNeuBildanzeige)
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBox_2)
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_19)
        self.plainTextEditRemarks = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEditRemarks.setObjectName(_fromUtf8("plainTextEditRemarks"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.plainTextEditRemarks)
        self.gridLayout_2.addLayout(self.formLayout_5, 3, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditNeuTitel = QtGui.QLineEdit(Dialog)
        self.lineEditNeuTitel.setObjectName(_fromUtf8("lineEditNeuTitel"))
        self.gridLayout.addWidget(self.lineEditNeuTitel, 0, 1, 1, 1)
        self.lineEditNeuCD = QtGui.QLineEdit(Dialog)
        self.lineEditNeuCD.setObjectName(_fromUtf8("lineEditNeuCD"))
        self.gridLayout.addWidget(self.lineEditNeuCD, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.pushButtonOriginalAlt = QtGui.QPushButton(Dialog)
        self.pushButtonOriginalAlt.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/appointment-recurring.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonOriginalAlt.setIcon(icon10)
        self.pushButtonOriginalAlt.setAutoDefault(True)
        self.pushButtonOriginalAlt.setObjectName(_fromUtf8("pushButtonOriginalAlt"))
        self.gridLayout.addWidget(self.pushButtonOriginalAlt, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditNeuBild = QtGui.QLineEdit(Dialog)
        self.lineEditNeuBild.setReadOnly(True)
        self.lineEditNeuBild.setObjectName(_fromUtf8("lineEditNeuBild"))
        self.gridLayout.addWidget(self.lineEditNeuBild, 3, 1, 1, 1)
        self.lineEditNeuOriginal = QtGui.QLineEdit(Dialog)
        self.lineEditNeuOriginal.setObjectName(_fromUtf8("lineEditNeuOriginal"))
        self.gridLayout.addWidget(self.lineEditNeuOriginal, 4, 1, 1, 1)
        self.pushButtonOriginal = QtGui.QPushButton(Dialog)
        self.pushButtonOriginal.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/go-next.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOriginal.setIcon(icon11)
        self.pushButtonOriginal.setObjectName(_fromUtf8("pushButtonOriginal"))
        self.gridLayout.addWidget(self.pushButtonOriginal, 4, 6, 1, 1)
        self.label_1 = QtGui.QLabel(Dialog)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditNeuDarsteller = QtGui.QLineEdit(Dialog)
        self.lineEditNeuDarsteller.setToolTip(_fromUtf8(""))
        self.lineEditNeuDarsteller.setObjectName(_fromUtf8("lineEditNeuDarsteller"))
        self.gridLayout.addWidget(self.lineEditNeuDarsteller, 1, 1, 1, 1)
        self.pushButtonAddYear = QtGui.QPushButton(Dialog)
        self.pushButtonAddYear.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/x-office-calendar-symbolic.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddYear.setIcon(icon12)
        self.pushButtonAddYear.setObjectName(_fromUtf8("pushButtonAddYear"))
        self.gridLayout.addWidget(self.pushButtonAddYear, 4, 4, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxYear = QtGui.QComboBox(Dialog)
        self.comboBoxYear.setObjectName(_fromUtf8("comboBoxYear"))
        self.gridLayout.addWidget(self.comboBoxYear, 4, 3, 1, 1)
        self.pushButtonRepeat = QtGui.QPushButton(Dialog)
        self.pushButtonRepeat.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/repeat.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRepeat.setIcon(icon13)
        self.pushButtonRepeat.setObjectName(_fromUtf8("pushButtonRepeat"))
        self.gridLayout.addWidget(self.pushButtonRepeat, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditNeuTitel, self.lineEditNeuDarsteller)
        Dialog.setTabOrder(self.lineEditNeuDarsteller, self.lineEditNeuCD)
        Dialog.setTabOrder(self.lineEditNeuCD, self.lineEditNeuBild)
        Dialog.setTabOrder(self.lineEditNeuBild, self.lineEditNeuOriginal)
        Dialog.setTabOrder(self.lineEditNeuOriginal, self.pushButtonOriginalAlt)
        Dialog.setTabOrder(self.pushButtonOriginalAlt, self.comboBoxYear)
        Dialog.setTabOrder(self.comboBoxYear, self.pushButtonAddYear)
        Dialog.setTabOrder(self.pushButtonAddYear, self.pushButtonOriginal)
        Dialog.setTabOrder(self.pushButtonOriginal, self.radioButtonVorhandenJa)
        Dialog.setTabOrder(self.radioButtonVorhandenJa, self.radioButtonVorhandenNein)
        Dialog.setTabOrder(self.radioButtonVorhandenNein, self.radioButtonGesehenJa)
        Dialog.setTabOrder(self.radioButtonGesehenJa, self.radioButtonGesehenNein)
        Dialog.setTabOrder(self.radioButtonGesehenNein, self.radioButtonCoverJa)
        Dialog.setTabOrder(self.radioButtonCoverJa, self.radioButtonCoverNein)
        Dialog.setTabOrder(self.radioButtonCoverNein, self.checkBoxUninteressant)
        Dialog.setTabOrder(self.checkBoxUninteressant, self.comboBoxDefinition)
        Dialog.setTabOrder(self.comboBoxDefinition, self.spinBoxF)
        Dialog.setTabOrder(self.spinBoxF, self.spinBoxH)
        Dialog.setTabOrder(self.spinBoxH, self.spinBoxT)
        Dialog.setTabOrder(self.spinBoxT, self.spinBoxC)
        Dialog.setTabOrder(self.spinBoxC, self.spinBoxX)
        Dialog.setTabOrder(self.spinBoxX, self.spinBoxO)
        Dialog.setTabOrder(self.spinBoxO, self.spinBoxV)
        Dialog.setTabOrder(self.spinBoxV, self.spinBoxB)
        Dialog.setTabOrder(self.spinBoxB, self.spinBoxA)
        Dialog.setTabOrder(self.spinBoxA, self.spinBoxS)
        Dialog.setTabOrder(self.spinBoxS, self.spinBoxK)
        Dialog.setTabOrder(self.spinBoxK, self.pushButtonNeuDarstelleruebernehmen)
        Dialog.setTabOrder(self.pushButtonNeuDarstelleruebernehmen, self.listWidgetW)
        Dialog.setTabOrder(self.listWidgetW, self.listWidgetM)
        Dialog.setTabOrder(self.listWidgetM, self.pushButtonBildbeschneiden)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "New / Change / Delete", None))
        self.groupBox_4.setTitle(_translate("Dialog", "present", None))
        self.radioButtonVorhandenJa.setWhatsThis(_translate("Dialog", "Mark here when video is present.", None))
        self.radioButtonVorhandenJa.setText(_translate("Dialog", "yes", None))
        self.radioButtonVorhandenNein.setWhatsThis(_translate("Dialog", "Mark here when video is NOT present.", None))
        self.radioButtonVorhandenNein.setText(_translate("Dialog", "no", None))
        self.groupBox_5.setTitle(_translate("Dialog", "watched", None))
        self.radioButtonGesehenJa.setWhatsThis(_translate("Dialog", "Mark here when this video has been watched.", None))
        self.radioButtonGesehenJa.setText(_translate("Dialog", "yes", None))
        self.radioButtonGesehenNein.setWhatsThis(_translate("Dialog", "Mark here when this video has NOT yet watched.", None))
        self.radioButtonGesehenNein.setText(_translate("Dialog", "no", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Cover", None))
        self.radioButtonCoverJa.setWhatsThis(_translate("Dialog", "Mark here when the image to be added in database is a video cover.", None))
        self.radioButtonCoverJa.setText(_translate("Dialog", "yes", None))
        self.radioButtonCoverNein.setWhatsThis(_translate("Dialog", "Mark here when the image to be added in database is NOT a video cover.", None))
        self.radioButtonCoverNein.setText(_translate("Dialog", "no", None))
        self.label_8.setText(_translate("Dialog", "Title in clipboard:", None))
        self.checkBoxUninteressant.setWhatsThis(_translate("Dialog", "Check this box, if you did not like the movie", None))
        self.checkBoxUninteressant.setText(_translate("Dialog", "Not interesting", None))
        self.label_17.setWhatsThis(_translate("Dialog", "Please select the resolution of the clip.", None))
        self.label_17.setText(_translate("Dialog", "Resolution:", None))
        self.comboBoxDefinition.setItemText(1, _translate("Dialog", "SD", None))
        self.comboBoxDefinition.setItemText(2, _translate("Dialog", "HD 720p", None))
        self.comboBoxDefinition.setItemText(3, _translate("Dialog", "HD 1080p", None))
        self.comboBoxDefinition.setItemText(4, _translate("Dialog", "UltraHD", None))
        self.comboBoxDefinition.setItemText(5, _translate("Dialog", "Unknown", None))
        self.label_18.setText(_translate("Dialog", "Rating:", None))
        self.pushButtonClearRating.setToolTip(_translate("Dialog", "<html><head/><body><p>Clear rating</p></body></html>", None))
        self.label.setText(_translate("Dialog", "Facial", None))
        self.label_5.setText(_translate("Dialog", "Handjob", None))
        self.label_7.setText(_translate("Dialog", "Tits", None))
        self.label_9.setText(_translate("Dialog", "Cmp", None))
        self.label_10.setText(_translate("Dialog", "Analcmp", None))
        self.label_11.setText(_translate("Dialog", "Oralcmp", None))
        self.label_12.setText(_translate("Dialog", "Cunt", None))
        self.label_13.setText(_translate("Dialog", "Belly", None))
        self.label_14.setText(_translate("Dialog", "Ass", None))
        self.label_15.setText(_translate("Dialog", "Others", None))
        self.label_16.setText(_translate("Dialog", "None", None))
        self.pushButtonNeuDarstelleruebernehmen.setToolTip(_translate("Dialog", "<html><head/><body><p>Adopt actor</p></body></html>", None))
        self.pushButtonNeuDarstelleruebernehmen.setWhatsThis(_translate("Dialog", "Copy the marked actors to the actors field", None))
        self.listWidgetW.setWhatsThis(_translate("Dialog", "Last used female actors. Adopt marked actors with a doubleclick or click on the button above.", None))
        self.listWidgetM.setWhatsThis(_translate("Dialog", "Last used male actors. Adopt marked actors with a doubleclick or click on the button above.", None))
        self.pushButtonBildbeschneiden.setToolTip(_translate("Dialog", "<html><head/><body><p>Crop image</p></body></html>", None))
        self.pushButtonBildbeschneiden.setWhatsThis(_translate("Dialog", "Crop image.\n"
"\n"
"How does cropping work?\n"
"\n"
"First click with the left mouse button in the left top corner, then click with the right mouse button at the bottom right.", None))
        self.pushButtonBildloeschen.setToolTip(_translate("Dialog", "<html><head/><body><p>Delete image file from working directory</p></body></html>", None))
        self.pushButtonBildloeschen.setWhatsThis(_translate("Dialog", "Delete image file in working directory", None))
        self.pushButtonNeuOK.setToolTip(_translate("Dialog", "<html><head/><body><p>Save</p></body></html>", None))
        self.pushButtonNeuOK.setWhatsThis(_translate("Dialog", "Save", None))
        self.pushButtonNeuOK.setShortcut(_translate("Dialog", "Enter, Return", None))
        self.pushButtonNeuCancel.setToolTip(_translate("Dialog", "<html><head/><body><p>Cancel</p></body></html>", None))
        self.pushButtonNeuCancel.setWhatsThis(_translate("Dialog", "Cancel", None))
        self.pushButtonNeuDelete.setToolTip(_translate("Dialog", "<html><head/><body><p>Delete from database</p></body></html>", None))
        self.pushButtonNeuDelete.setWhatsThis(_translate("Dialog", "Entry in database will be deleted, inclusive image file", None))
        self.pushButtonVerz.setToolTip(_translate("Dialog", "<html><head/><body><p>Change working directory</p></body></html>", None))
        self.pushButtonVerz.setWhatsThis(_translate("Dialog", "Change the working directory", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Image", None))
        self.labelNeuBildanzeige.setWhatsThis(_translate("Dialog", "Preview", None))
        self.label_19.setText(_translate("Dialog", "Remarks:", None))
        self.lineEditNeuTitel.setWhatsThis(_translate("Dialog", "Enter file name", None))
        self.lineEditNeuCD.setWhatsThis(_translate("Dialog", "Enter directory", None))
        self.label_6.setText(_translate("Dialog", "Original", None))
        self.pushButtonOriginalAlt.setToolTip(_translate("Dialog", "<html><head/><body><p>Reuse last entered original title, Ctrl+Y</p></body></html>", None))
        self.pushButtonOriginalAlt.setWhatsThis(_translate("Dialog", "Reuse last entered original title", None))
        self.pushButtonOriginalAlt.setShortcut(_translate("Dialog", "Ctrl+Y", None))
        self.label_4.setText(_translate("Dialog", "Image", None))
        self.lineEditNeuBild.setWhatsThis(_translate("Dialog", "Enter file name of image file", None))
        self.lineEditNeuOriginal.setWhatsThis(_translate("Dialog", "Enter original title of the movie. For adding more titles, please press the button on the right side.", None))
        self.pushButtonOriginal.setToolTip(_translate("Dialog", "Enter more movie titles", None))
        self.pushButtonOriginal.setWhatsThis(_translate("Dialog", "Enter more movie titles", None))
        self.label_1.setText(_translate("Dialog", "Title", None))
        self.label_2.setText(_translate("Dialog", "Actor", None))
        self.lineEditNeuDarsteller.setWhatsThis(_translate("Dialog", "Enter the list of actors, separated by comma", None))
        self.pushButtonAddYear.setToolTip(_translate("Dialog", "<html><head/><body><p>Select year from the combo box on the left and add it to the original title, ALT+Q</p></body></html>", None))
        self.pushButtonAddYear.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Select year from the combo box on the left and add it to the original title<br/></p></body></html>", None))
        self.pushButtonAddYear.setShortcut(_translate("Dialog", "Alt+Q", None))
        self.label_3.setText(_translate("Dialog", "CD", None))
        self.pushButtonRepeat.setToolTip(_translate("Dialog", "<html><head/><body><p>Repeat you last input, F12</p></body></html>", None))
        self.pushButtonRepeat.setShortcut(_translate("Dialog", "F12", None))

