# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_suche_video.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 987, 664))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidgetVideo = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidgetVideo.setMinimumSize(QtCore.QSize(45, 0))
        self.listWidgetVideo.setMaximumSize(QtCore.QSize(45, 16777215))
        self.listWidgetVideo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidgetVideo.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetVideo.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidgetVideo.setObjectName("listWidgetVideo")
        self.horizontalLayout.addWidget(self.listWidgetVideo)
        self.listWidgetTitle = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidgetTitle.setObjectName("listWidgetTitle")
        self.horizontalLayout.addWidget(self.listWidgetTitle)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_insgesamt = QtWidgets.QLabel(Dialog)
        self.label_insgesamt.setText("")
        self.label_insgesamt.setObjectName("label_insgesamt")
        self.horizontalLayout_2.addWidget(self.label_insgesamt)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_vorhanden = QtWidgets.QLabel(Dialog)
        self.label_vorhanden.setText("")
        self.label_vorhanden.setObjectName("label_vorhanden")
        self.horizontalLayout_2.addWidget(self.label_vorhanden)
        spacerItem = QtWidgets.QSpacerItem(378, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonSuchen = QtWidgets.QPushButton(Dialog)
        self.pushButtonSuchen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pypordb/suchen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSuchen.setIcon(icon1)
        self.pushButtonSuchen.setObjectName("pushButtonSuchen")
        self.horizontalLayout_2.addWidget(self.pushButtonSuchen)
        self.pushButtonAnzeigen = QtWidgets.QPushButton(Dialog)
        self.pushButtonAnzeigen.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pypordb/video.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAnzeigen.setIcon(icon2)
        self.pushButtonAnzeigen.setObjectName("pushButtonAnzeigen")
        self.horizontalLayout_2.addWidget(self.pushButtonAnzeigen)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Dialog)
        self.pushButtonAbbrechen.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pypordb/dialog-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAbbrechen.setIcon(icon3)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.horizontalLayout_2.addWidget(self.pushButtonAbbrechen)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Search in existing movies"))
        self.listWidgetVideo.setToolTip(_translate("Dialog", "Presentation of the existing movies"))
        self.listWidgetVideo.setWhatsThis(_translate("Dialog", "Presentation of the existing movies"))
        self.label_2.setText(_translate("Dialog", "overall:"))
        self.label_3.setText(_translate("Dialog", "available:"))
        self.pushButtonSuchen.setToolTip(_translate("Dialog", "Start search (Ctrl+S)"))
        self.pushButtonSuchen.setWhatsThis(_translate("Dialog", "Starts searching"))
        self.pushButtonSuchen.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.pushButtonAnzeigen.setToolTip(_translate("Dialog", "<html><head/><body><p>Show movies (Ctrl+D)</p></body></html>"))
        self.pushButtonAnzeigen.setWhatsThis(_translate("Dialog", "Shows avaible movies"))
        self.pushButtonAnzeigen.setShortcut(_translate("Dialog", "Ctrl+D"))
        self.pushButtonAbbrechen.setToolTip(_translate("Dialog", "Cancel (Esc)"))

