pyuic4 -o pordb_hauptdialog.py pordb_hauptdialog.ui
pyuic4 -o pordb_neu.py pordb_neu.ui
pyuic4 -o pordb_cover.py pordb_cover.ui
pyuic4 -o pordb_pseudo.py pordb_pseudo.ui
pyuic4 -o pordb_suchen.py pordb_suchen.ui
pyuic4 -o pordb_bildschneiden.py pordb_bildschneiden.ui
pyuic4 -o pordb_bilddatei_umbenennen.py pordb_bilddatei_umbenennen.ui
pyuic4 -o pordb_darstellerneu.py pordb_darstellerneu.ui
pyuic4 -o pordb_darsteller_suchen.py pordb_darsteller_suchen.ui
pyuic4 -o pordb_darsteller_umbenennen.py pordb_darsteller_umbenennen.ui
pyuic4 -o pordb_darsteller_korrigieren.py pordb_darsteller_korrigieren.ui
pyuic4 -o pordb_bildgross.py pordb_bildgross.ui
pyuic4 -o pordb_land.py pordb_land.ui
pyuic4 -o pordb_suchbegriffe.py pordb_suchbegriffe.ui
pyuic4 -o pordb_suche_video.py pordb_suche_video.ui
pyuic4 -o pordb_historie.py pordb_historie.ui
pyuic4 -o pordb_original.py pordb_original.ui
pyuic4 -o pordb_bookmarks.py pordb_bookmarks.ui
pyuic4 -o pordb_iafd.py pordb_iafd.ui
pyuic4 -o pordb_devices.py pordb_devices.ui
